import {ArrowRight,BookOpen,ShieldCheck,ArrowUpRight} from 'lucide-react';
import {SiteLink as Link} from '@/components/site/site-link';
import {seo} from '@/lib/seo';
import {guides,guideTopics,privacyGuide} from '@/lib/guides';
import {ResourceLayout,ResourceCTA} from '@/components/site/resource-layout';
export const metadata=seo('Practical Guides — PDFs, Images, Grades & Code','Learn PDF quality trade-offs, image formats, credit-weighted grades, JSON and encoding. Original practical guides with examples and links to useful tools.','/blog/');
export default function Blog(){const featured=privacyGuide;return <ResourceLayout name="Guides & articles" path="/blog/" eyebrow="A LITTLE EXTRA CLARITY" title="Useful tools. Useful know-how." description="Understand the workflow, choose the right settings and know what to check in the result. Practical reading for everyday digital tasks.">
 <section className="guide-feature" aria-labelledby="featured-guide"><div className="guide-feature-art" aria-hidden="true"><div className="guide-document"><BookOpen/><i/><i/><i/><span><ShieldCheck/></span></div><span className="guide-art-label">ON YOUR DEVICE</span></div><div className="guide-feature-copy"><span className="eyebrow">FEATURED GUIDE · {featured.topic}</span><h2 id="featured-guide">{featured.title}</h2><p>{featured.description}</p><Link className="primary-button" href={featured.href}>Read the guide<ArrowRight size={17} aria-hidden="true"/></Link></div></section>
 <section className="resource-section" aria-labelledby="published-guides"><div className="resource-section-heading"><span className="eyebrow">PRACTICAL READING</span><h2 id="published-guides">Start with the question you need answered.</h2><p>These guides distinguish settings, formulas and limitations so you can choose the right tool and check its output.</p></div><div className="article-link-grid">{guides.filter(g=>g.slug!==featured.slug).map(g=><Link className="article-link" href={g.href} key={g.slug}><span className="eyebrow">{g.topic}</span><h3>{g.title}</h3><p>{g.description}</p><span className="text-link">Read guide<ArrowRight size={15} aria-hidden="true"/></span></Link>)}</div></section>
 <section className="resource-section" aria-labelledby="guide-topics"><div className="resource-section-heading"><span className="eyebrow">EXPLORE BY TASK</span><h2 id="guide-topics">Instructions beside the tools.</h2><p>Each collection links to working tools, task-specific instructions and supporting articles.</p></div><nav className="guide-topics" aria-label="Collections with tool instructions">{guideTopics.map(topic=><Link href={topic.href} key={topic.href}><h3>{topic.name}<ArrowUpRight size={17} aria-hidden="true"/></h3><p>{topic.text}</p><span>Explore collection</span></Link>)}</nav></section>
 <aside className="resource-editorial-note"><BookOpen size={21} aria-hidden="true"/><p>Examples explain a workflow or calculation, not a promised result. Tool capabilities are documented on the corresponding pages; review important outputs and keep your originals.</p></aside><ResourceCTA title="Put the know-how to work." description="Go from a useful explanation to the tool you need, with the same clear workflow."/>
 </ResourceLayout>}
