// Category hubs answer workflow questions without competing with a single tool URL.
export const categoryContent:Record<string,{primary:string;secondary:string[];longTail:string[];workflows:{title:string;text:string;tools:string[]}[];guides:string[]}>= {
 'pdf-tools':{primary:'PDF tools online',secondary:['browser PDF utilities','PDF document workflows'],longTail:['PDF page tools without uploading documents','choose PDF conversion or OCR'],workflows:[
  {title:'Prepare a submission',text:'Arrange the files and check document junctions before judging the final size. Extract unnecessary pages rather than sacrificing readability. Page-copy operations do not guarantee preservation of forms, bookmarks or digital signatures; review those requirements separately.',tools:['pdf-merger','pdf-splitter','pdf-compressor']},
  {title:'Choose editable text or recognition',text:'Native PDF text belongs in PDF to Word. Scanned pages need the separate OCR workflow. Both need review, but recognition errors and conversion-layout differences are different problems. OCR exports text or DOCX; it does not add a searchable-PDF layer.',tools:['pdf-to-word','pdf-ocr','word-to-pdf']},
  {title:'Work with page appearance',text:'Export a page image for a slide or visual attachment, or embed JPG and PNG images into PDF pages. Rotate a sideways page without flattening it. A page picture captures visible content but is not editable document text.',tools:['pdf-to-jpg','jpg-to-pdf','rotate-pdf']}
 ],guides:['reduce-pdf-file-size-without-losing-quality','make-pdf-editable-native-text-or-ocr','combine-pdf-files-in-the-right-order','scanned-vs-searchable-pdf']},
 'image-tools':{primary:'online image tools',secondary:['image editing utilities','browser image preparation'],longTail:['choose image resize compression or conversion','image tools with local processing'],workflows:[
  {title:'Meet an upload requirement',text:'Check accepted format, pixel dimensions and byte limit separately. Crop the intended frame, resize with proportions preserved, then compare compression choices. A correct width does not prove the file fits the byte limit.',tools:['image-cropper','image-resizer','image-compressor']},
  {title:'Choose a delivery format',text:'A photograph, text-heavy screenshot and transparent logo need different trade-offs. JPEG removes transparency; PNG can be larger; WebP needs destination support. Converting cannot restore detail that an earlier JPEG encoding discarded.',tools:['image-converter','png-to-jpg','jpg-to-png','webp-converter']},
  {title:'Prepare a document image',text:'Keep page edges, small print and orientation readable before creating a PDF or recognizing text. OCR is a transcription to check against the source, not a promise of error-free reading or exact layout reconstruction.',tools:['image-to-text','jpg-to-pdf','image-cropper']}
 ],guides:['jpeg-png-webp-which-format','image-dimensions-vs-file-size','jpg-png-to-pdf-page-size-margins']},
 'student-tools':{primary:'student grade calculators',secondary:['academic progress calculators','GPA marks attendance tools'],longTail:['student calculators with custom grade points','credit weighting versus marks percentage'],workflows:[
  {title:'Understand credit-weighted grades',text:'GPA weights course grade points by credits. CGPA combines included study using its credit totals. Use the institution’s scale and repeat-course policy; an online estimate is not an official transcript or a universal CGPA-to-percentage conversion.',tools:['gpa-calculator','cgpa-calculator']},
  {title:'Plan a target with the right totals',text:'A marks target depends on the remaining assessment total. An attendance target depends on future sessions changing both attended and conducted counts. Check whether enough eligible future marks or classes remain to achieve the target.',tools:['marks-calculator','attendance-calculator','percentage-calculator']},
  {title:'Build a custom admission aggregate',text:'Use the current weights and eligible components supplied by the university. The calculator does not retrieve admission policies, closing merit or official conversion formulas. Keep raw marks, percentages and grade points distinctly labeled.',tools:['university-merit-calculator','percentage-calculator','marks-calculator']}
 ],guides:['gpa-vs-cgpa-credit-weighted','attendance-percentage-target-classes','percentage-vs-percentage-points']},
 'finance-tools':{primary:'everyday financial calculators',secondary:['money and journey estimates','free numerical calculators'],longTail:['gross salary and monthly payment estimates','fuel cost with custom units and prices'],workflows:[
  {title:'Make percentage bases explicit',text:'Discount uses the original price. Profit margin divides by revenue, while markup divides by cost. Different denominators produce different percentages. Enter the costs that matter and remember that taxes or added fees may be outside the model.',tools:['discount-calculator','profit-calculator','percentage-calculator']},
  {title:'Compare monthly assumptions',text:'Loan payments assume a fixed rate and monthly schedule. Savings assumes constant growth and end-of-month deposits. Gross salary conversions use your work schedule. These are input scenarios, not lender quotes, take-home pay or promised returns.',tools:['loan-emi-calculator','savings-calculator','salary-calculator']},
  {title:'Keep dates and units consistent',text:'Fuel estimates need compatible distance, consumption and price units; US and Imperial gallons differ. Calendar age uses a selected as-of date rather than a fixed days-per-year division. Use your own prices and the actual cutoff date required by the task.',tools:['fuel-cost-calculator','age-calculator']}
 ],guides:['percentage-vs-percentage-points','browser-tools-and-privacy']},
 'text-tools':{primary:'online text utilities',secondary:['text counting and cleanup tools','case and line utilities'],longTail:['Unicode character counts without uploading text','clean pasted text while keeping paragraphs'],workflows:[
  {title:'Use the required counting rule',text:'Whitespace-separated words, Unicode code points and visible symbols are different counts. Compare the exact same pasted content and the rule required by the destination. Reading time is a fixed-speed estimate rather than a reader measurement.',tools:['word-counter','character-counter']},
  {title:'Change presentation carefully',text:'Mechanical casing can help labels and drafts, but names and acronyms still need review. Whitespace cleanup should preserve paragraph meaning. Keep the source alongside the result so a tidy appearance does not conceal lost structure.',tools:['case-converter','text-cleaner']},
  {title:'Clean lists without changing their meaning',text:'Duplicate removal keeps the first matching line under selected case and whitespace rules. Repetition can be intentional, and a line is not a structured database record. Check which entries disappeared before replacing the source.',tools:['remove-duplicate-lines','text-cleaner','word-counter']}
 ],guides:['word-character-count-unicode','browser-tools-and-privacy']},
 'developer-tools':{primary:'browser developer utilities',secondary:['data formatting and encoding tools','JSON UUID color utilities'],longTail:['validate JSON and escape URL components locally','UTF-8 encoding without an external API'],workflows:[
  {title:'Inspect data before replacing it',text:'Syntax-valid JSON can still have the wrong schema. JavaScript parsing can lose large-number precision and retains later duplicate keys. Keep the original payload and check the data contract, not just the neatness of formatted output.',tools:['json-formatter','uuid-generator']},
  {title:'Encode the correct boundary',text:'Base64 represents bytes as text; percent encoding protects a URL component. Neither encrypts a secret. Avoid encoding an entire URL or repeatedly decoding until a string looks familiar. Match the layers defined by the protocol.',tools:['base64-encoder-decoder','url-encoder-decoder','json-formatter']},
  {title:'Generate and convert with clear limits',text:'Random UUIDs are identifiers, not authorization. Color notations can round, particularly alpha values, and the preview is not a contrast certification. Review the format expected by the receiving code or design workflow.',tools:['uuid-generator','color-converter']}
 ],guides:['fix-invalid-json','base64-vs-url-encoding','browser-tools-and-privacy']},
 'generators':{primary:'free browser generators',secondary:['QR password and number generators','local PDF invoice generation'],longTail:['static QR codes without tracking redirects','generate outputs without saved user records'],workflows:[
  {title:'Create a code people can use',text:'A static QR code contains the link or text you enter. Preserve its quiet zone and square proportions, and test the final printed version. Destination availability is separate from scanning success; a static graphic does not update itself.',tools:['qr-code-generator']},
  {title:'Keep randomness in its proper role',text:'Password, random-number and UUID generation use browser cryptographic randomness. Safe storage, access control and a verified public-draw process are separate responsibilities. Generated values are not kept in Tool Fera history.',tools:['password-generator','random-number-generator','uuid-generator']},
  {title:'Review a document before issuing it',text:'A simple PDF invoice uses your business details, line items and entered tax rate. It is not an accounting database or legal-compliance certificate. Check required fields and totals, then keep your own issued records.',tools:['invoice-generator','discount-calculator','profit-calculator']}
 ],guides:['qr-code-not-scanning-print-checklist','browser-tools-and-privacy','percentage-vs-percentage-points']}
};
