export const information:Record<string,{title:string;description:string}>={
 about:{title:'About Tool Fera — Everyday Browser Utilities',description:'Get to know Tool Fera: practical PDF, image, OCR, text, developer, student and calculation tools with clear workflows and on-device processing.'},
 contact:{title:'Help & Contact',description:'Troubleshoot file errors, supported formats, browser limits and mobile use. See Tool Fera’s current support and contact availability.'},
 'privacy-policy':{title:'Privacy Policy',description:'How Tool Fera handles selected files, on-device tool inputs, browser storage, favorite tool IDs and website delivery requests.'},
 'terms-of-use':{title:'Terms of Use',description:'Plain-language terms for using Tool Fera, including permitted use, content responsibility, availability and the limits of utility results.'},
 disclaimer:{title:'Disclaimer',description:'Review Tool Fera’s document conversion, OCR, compression and calculation limitations before relying on important results.'}
};
export type LegalSection={id:string;title:string;paragraphs:string[]};
export const legalContent:Record<string,{intro:string;callout:{title:string;text:string};sections:LegalSection[]}>= {
 'privacy-policy':{
  intro:'This policy describes the current Tool Fera application. It separates the content you process from the small list of tools your browser remembers and the requests used to deliver the website.',
  callout:{title:'Your content and your toolkit history are different.',text:'The current file and text tools process selected content on your device. Favorites and recent history store tool IDs in this browser, not the contents of your files or tool inputs.'},
  sections:[
   {id:'files',title:'Files and tool inputs',paragraphs:['Current PDF, image, document conversion, OCR, text, calculation and generator tools process their inputs in the browser. Their processing code does not transmit selected files, typed text or calculation values to a remote conversion service. Choosing a file gives the page permission to read that selected file; it is not a server upload.','Tool content and generated previews are held in the current page’s memory. Temporary download and preview links are created in the browser. Resetting a tool or leaving its page releases the resources managed by that tool. A file you download is saved by your browser and remains under your control. Keep your originals and manage downloads separately.']},
   {id:'storage',title:'Favorites, recent tools and browser storage',paragraphs:['Tool Fera uses localStorage for favorite and recently used tool identifiers. These lists do not include document contents, images, grades, calculation values, generated passwords or OCR text. They belong to that browser profile and are not synced through a Tool Fera account.','The saved lists can remain until you use “Clear favorites & history” on the homepage or remove site data in browser settings. Other people using the same browser profile may see the list. Storage restrictions or private browsing can prevent it from persisting. Browser-managed caches may retain downloaded website assets separately from these lists.']},
   {id:'delivery',title:'Website delivery and technical requests',paragraphs:['Your browser makes network requests to load pages, JavaScript, images and processing assets such as PDF workers, OCR language data and document fonts. These requests serve the application; the tool processing code does not attach your selected file contents or typed tool inputs to them.','The hosting platform receives the information needed to handle those requests, which can include an IP address, browser information and requested URL. Platform access controls and operational logs are separate from Tool Fera’s local utility processing. This policy does not promise a retention period for hosting logs that Tool Fera does not configure.']},
   {id:'tracking',title:'Accounts, cookies, analytics and advertising',paragraphs:['The current Tool Fera application has no user account system, user database, payment flow, advertising scripts or application analytics. It does not set application tracking cookies. Local favorites/history use browser storage rather than a user database.','Hosting-platform access mechanisms can have their own storage and requests. Browser extensions, browser vendors and software outside Tool Fera are outside the application’s control. The absence of Tool Fera tracking scripts is not a claim that the entire hosting or browser environment has no technical data handling.']},
   {id:'links',title:'Links and other services',paragraphs:['If you follow an external link, that destination’s practices apply. Tool Fera does not send your tool inputs to external links as part of the current processing workflow. Avoid placing confidential content in a page URL or processing it in a browser profile shared with others.']},
   {id:'updates',title:'Policy updates and privacy questions',paragraphs:['The date above identifies this policy revision. If Tool Fera adds a workflow that sends content to a server or introduces analytics, accounts or other data collection, its processing explanation and this policy should be updated to describe it.','There is currently no public support email or submission form in this application. The Help & Contact page provides current support availability and guidance for clearing browser history and troubleshooting tools.']}
  ]
 },
 'terms-of-use':{
  intro:'Tool Fera provides practical browser utilities. These terms explain how to use them responsibly and what to check before depending on a result.',
  callout:{title:'Keep the original. Review the result.',text:'You remain responsible for the material you process and how you use an output. Tool limits and a successful download do not guarantee that a result is suitable for an important decision.'},
  sections:[
   {id:'use',title:'Using Tool Fera',paragraphs:['By using Tool Fera, you agree to use the website under these terms. Current tools are free and do not require a Tool Fera application account. Review the instructions and limitations shown on the specific tool you choose.']},
   {id:'permitted',title:'Permitted use and responsible conduct',paragraphs:['Use the tools for material you are authorized to access, process and share. Do not use the website to break applicable laws, violate another person’s rights, distribute harmful content, exploit vulnerabilities or interfere with the service or other users.']},
   {id:'content',title:'Your inputs and generated content',paragraphs:['You retain responsibility for your source files, text and other inputs. Using a tool does not transfer ownership of your content to Tool Fera or grant rights to third-party material you did not already have. Review outputs before sending, publishing or submitting them, and keep backups of important originals.']},
   {id:'limits',title:'Tool and browser limitations',paragraphs:['File formats, document features, device memory and browser capabilities affect what a tool can process. Tool pages state their current input and resource limits. Processing can fail or produce a result that differs from the original. No exact document layout, OCR accuracy, compression saving or calculation outcome is guaranteed.']},
   {id:'availability',title:'Availability and changes',paragraphs:['Tool Fera is provided as available. Pages, tools and supported features may change or become unavailable. There is no promise of uninterrupted access, permanent compatibility with every browser, or recovery of content held only in a page’s temporary memory.']},
   {id:'results',title:'Accuracy and important decisions',paragraphs:['Outputs are practical aids, not official records or professional advice. Check conversions, recognized text and calculations independently when the result affects an academic, financial, legal or other important decision. The Disclaimer explains common limitations in more detail.']},
   {id:'site-content',title:'Website content and third-party materials',paragraphs:['The website includes Tool Fera branding, guides and software, alongside third-party open-source components. Applicable rights and licenses continue to apply. Using a tool does not grant ownership of the website’s branding or permission to disregard third-party license requirements.']},
   {id:'external',title:'External links',paragraphs:['Links to another service do not guarantee its availability, accuracy or practices. Review that service’s own terms and privacy information before using it.']},
   {id:'liability',title:'Responsibility and liability',paragraphs:['You decide whether a tool and its output meet your needs. To the extent applicable law permits, Tool Fera does not provide warranties about suitability, accuracy or uninterrupted availability, and does not accept liability for loss caused by relying on utility outputs or unavailable tools. These terms do not exclude rights or responsibilities that cannot lawfully be excluded.']},
   {id:'changes',title:'Updates and support availability',paragraphs:['These terms may be revised as the product changes; the date above identifies the current revision. Read the Privacy Policy for current data handling and Help & Contact for available guidance. The application currently has no public support email or contact form.']}
  ]
 },
 disclaimer:{
  intro:'A useful output still deserves a check. These are the practical limits to consider when using Tool Fera for everyday work or important files.',
  callout:{title:'Review before you rely.',text:'Keep an unchanged original, inspect the generated result and verify important information independently. Tool Fera is not a substitute for professional advice or an official record.'},
  sections:[
   {id:'documents',title:'Document conversion and layout',paragraphs:['PDF and Word documents can contain layouts, fonts, page boundaries, tables, images and drawings that do not convert exactly. Editable text and complex page layouts can differ between applications. Inspect every important page, including headers, footers, diagrams and tables, before sharing or submitting a converted file.']},
   {id:'ocr',title:'OCR and recognized text',paragraphs:['OCR can misread characters, omit text or interpret reading order incorrectly. Small print, low-resolution images, rotation and complicated layouts can reduce recognition quality. Check names, dates, amounts and other important details against the original rather than treating recognized text as authoritative.']},
   {id:'quality',title:'Compression and image processing',paragraphs:['Compression and format conversion can alter visual quality, transparency, color or dimensions. Some files are already optimized and cannot be made meaningfully smaller with the available settings. Review previews and actual file-size comparisons. A smaller result is not automatically the best result for your intended use.']},
   {id:'calculations',title:'Calculations and academic results',paragraphs:['Calculators use the values, units and assumptions you provide. Academic grade and merit rules differ by institution; financial estimates can omit real-world costs or use simplified assumptions. Confirm the tool’s explanation and use official sources when you need an official grade, admission result, rate or record.']},
   {id:'generated',title:'Text, code and generated outputs',paragraphs:['Formatting, encoding and generated documents can have application-specific limits. JSON number handling can be affected by JavaScript precision. Keep generated passwords secure, and check invoices, QR codes and other outputs before using them.']},
   {id:'advice',title:'Professional advice and backups',paragraphs:['Tool Fera does not provide legal, tax, investment, medical or other professional advice. Consult an appropriate professional when your situation requires it. Keep originals and backups of important files; a temporary preview or download link is not permanent storage.']}
  ]
 }
};
