// Lightweight registry shared by search, navigation and browser history.
export type FAQ = {question:string;answer:string};
export type Tool = {id:string;slug:string;name:string;category:string;description:string;icon:string;keywords:string[];kind?:string;intro?:string;steps?:string[];help?:string;faq?:FAQ[];related?:string[]};
export const toolCategories = [
 {slug:'pdf-tools',name:'PDF Tools',icon:'pdf'}, {slug:'image-tools',name:'Image Tools',icon:'image'}, {slug:'student-tools',name:'Student Tools',icon:'student'}, {slug:'finance-tools',name:'Calculators',icon:'finance'}, {slug:'text-tools',name:'Text Tools',icon:'text'}, {slug:'developer-tools',name:'Developer Tools',icon:'code'}, {slug:'generators',name:'Generators',icon:'generator'}
];
const rows:[string,string,string,string,string?,string[]?][] = [
 ['pdf-tools','pdf-compressor','PDF Compressor','Compress a PDF and compare the actual savings.','pdf-compress',['compress pdf','reduce pdf size']],['pdf-tools','pdf-merger','PDF Merger','Bring multiple PDFs into one document.','pdf', ['merge pdf','combine pdfs']],['pdf-tools','pdf-splitter','PDF Splitter','Extract the pages you actually need.','pdf',['split pdf','extract pdf pages']],['pdf-tools','pdf-to-jpg','PDF to PNG/JPG','Export PDF pages as JPG or PNG images.','pdf-images-out',['pdf to images','pdf to png','pdf to jpg','pdf to jpeg']],['pdf-tools','jpg-to-pdf','PNG/JPG to PDF','Combine JPG and PNG images into a PDF.','pdf-images-in',['images to pdf','png to pdf','jpg to pdf','jpeg to pdf']],['pdf-tools','pdf-to-word','PDF to Word','Convert PDF text into editable Word with preserved page layout.','pdf-word',['pdf to docx','convert pdf to word','editable pdf to word']],
 ['pdf-tools','pdf-ocr','PDF OCR','Extract structured English text from scanned PDF pages.','pdf-ocr',['scanned pdf','scan to text','pdf ocr','recognize pdf']],
 ['pdf-tools','word-to-pdf','Word to PDF','Create a PDF from a DOCX with selectable text.','word-pdf',['docx to pdf','convert word to pdf','word document']],
 ['pdf-tools','rotate-pdf','Rotate PDF','Turn selected pages the right way up.','pdf',['rotate pages']],['pdf-tools','delete-pdf-pages','Delete PDF Pages','Remove unwanted pages from a document.','pdf'],['pdf-tools','reorder-pdf-pages','Reorder PDF Pages','Arrange every page in your preferred order.','pdf'],
 ['image-tools','image-compressor','Image Compressor','Compress, compare and download a lighter image.','image',['compress photo','reduce image size']],['image-tools','image-resizer','Image Resizer','Set dimensions, choose a format and resize precisely.','image',['resize image','photo dimensions']],['image-tools','image-converter','Image Converter','Convert between supported image formats locally.','image',['convert image','jpg to png','png to webp','jpeg','avif','bmp']],['image-tools','image-cropper','Image Cropper','Select precise pixels and export a cropped image.','image',['crop photo','crop image']],['image-tools','jpg-to-png','JPG to PNG','Convert photographs to PNG format.','image'],['image-tools','png-to-jpg','PNG to JPG','Make a JPEG from your PNG image.','image'],['image-tools','webp-converter','WebP Converter','Switch images to a modern web format.','image'],['image-tools','image-to-text','Image to Text OCR','Extract readable text from an image.','image-ocr'],
 ['student-tools','gpa-calculator','GPA Calculator','Calculate your credit-weighted semester GPA.','gpa'],['student-tools','cgpa-calculator','CGPA Calculator','See your overall academic progress.','cgpa'],['student-tools','percentage-calculator','Percentage Calculator','Quick answers for everyday percentages.','percentage',['percent','marks percentage']],['student-tools','marks-calculator','Marks Calculator','Work out totals and target marks.','marks'],['student-tools','attendance-calculator','Attendance Calculator','Stay on top of your attendance target.','attendance'],
 ['finance-tools','fuel-cost-calculator','Fuel Cost Calculator','Estimate journey costs in your own units.','fuel',['petrol','diesel','fuel price']],['student-tools','university-merit-calculator','University Merit Calculator','Explore admission aggregate calculations.','merit'],
 ['finance-tools','age-calculator','Age Calculator','Calculate age between two calendar dates.','age',['birthday','date of birth']],
 ['finance-tools','loan-emi-calculator','Loan / EMI Calculator','Estimate regular loan repayments.','loan'],['finance-tools','savings-calculator','Savings Calculator','Project your savings over time.','savings'],['finance-tools','profit-calculator','Profit Calculator','Calculate profit and profit margin.','profit'],['finance-tools','discount-calculator','Discount Calculator','Find the price after a discount.','discount'],['finance-tools','salary-calculator','Salary Calculator','Compare monthly and annual earnings.','salary'],
 ['text-tools','word-counter','Word Counter','Count words, characters and reading time.','word',['character counter','text count']],['text-tools','character-counter','Character Counter','Check character limits at a glance.','word',['count characters','text length']],['text-tools','case-converter','Case Converter','Switch between common text cases.','case'],['text-tools','remove-duplicate-lines','Remove Duplicate Lines','Keep one copy of each unique line.','duplicates'],['text-tools','text-cleaner','Text Cleaner','Tidy spaces and clean up pasted text.','clean'],
 ['developer-tools','json-formatter','JSON Formatter','Validate, format and minify your JSON.','json',['beautify json','json validator']],['developer-tools','base64-encoder-decoder','Base64 Encoder / Decoder','Encode or decode Unicode text as Base64.','base64'],['developer-tools','url-encoder-decoder','URL Encoder / Decoder','Escape and decode URL components.','url'],['developer-tools','uuid-generator','UUID Generator','Create unique identifiers for your projects.','uuid'],['developer-tools','color-converter','Color Converter','Convert between HEX, RGB and HSL.','color'],
 ['generators','qr-code-generator','QR Code Generator','Turn a link or text into a scannable code.','qr',['qr','qrcode']],['generators','password-generator','Password Generator','Create a strong, random password.','password',['secure password']],['generators','random-number-generator','Random Number Generator','Pick a number within your chosen range.','random'],['generators','invoice-generator','Invoice Generator','Create a clear invoice for your work.','invoice']
];
export const toolDefinitions:Tool[] = rows.map(([category,slug,name,description,kind,keywords])=>({id:slug,slug,name,category,description,kind,icon:toolCategories.find(c=>c.slug===category)!.icon,keywords:[name.toLowerCase(),slug.replaceAll('-',' '),...(keywords||[])]}));
export const toolUrl=(t:Tool)=>`/${t.category}/${t.slug}/`;
export const getTool=(id:string)=>toolDefinitions.find(t=>t.id===id);
export const categoryTools=(slug:string)=>toolDefinitions.filter(t=>t.category===slug || (slug==='finance-tools' && t.id==='percentage-calculator'));
export const availableTools=(slug?:string)=>(slug?categoryTools(slug):toolDefinitions).filter(t=>!!t.kind);
export const popularIds=['image-compressor','pdf-merger','percentage-calculator','word-counter','pdf-to-jpg','json-formatter','qr-code-generator','fuel-cost-calculator'];
