'use client';
import {useId,useState} from 'react';
import {Plus,Trash2} from 'lucide-react';
import {marksResult,attendanceResult,meritResult,loanResult,savingsResult,profitResult,salaryResult} from '@/tools/additional-calculations';
import {CopyButton,ResetButton} from './action-button';
const number=(value:string)=>value.trim()===''?NaN:Number(value);
const format=(value:number)=>value.toLocaleString('en-US',{maximumFractionDigits:2});
function Field({label,value,onChange,min=0,max,step='any',placeholder}:{label:string;value:string;onChange:(value:string)=>void;min?:number;max?:number;step?:string;placeholder?:string}){const id=useId();return <div><label htmlFor={id} className="field-label">{label}</label><input id={id} className="field-input" type="number" inputMode="decimal" value={value} placeholder={placeholder} min={min} max={max} step={step} onChange={event=>onChange(event.target.value)}/></div>}
const configs:Record<string,{labels:string[];examples:string[];note:string}>={
 marks:{labels:['Marks obtained so far','Total marks completed','Marks still available','Target overall (%)'],examples:['80','100','100','75'],note:'Marks use the same units. Target estimates include the remaining marks; rounding policies can differ.'},
 attendance:{labels:['Classes attended','Classes held','Attendance target (%)'],examples:['30','40','75'],note:'Future-class estimates assume you attend every additional class. Cancelled classes and institution policies can differ.'},
 loan:{labels:['Loan amount','Annual interest rate (%)','Term (months)'],examples:['10000','6','24'],note:'Fixed-rate, equal monthly payments. No fees, taxes, insurance or early repayments are included.'},
 savings:{labels:['Starting balance','Monthly contribution','Annual return (%)','Years'],examples:['1000','100','5','5'],note:'Monthly compounding, with contributions at the end of each month. Constant return is an assumption; taxes, fees and inflation are excluded.'},
 profit:{labels:['Revenue','Total cost'],examples:['1000','700'],note:'Enter revenue and costs in the same currency. Margin uses revenue; markup uses cost. Include all costs that matter to your estimate.'},
 salary:{labels:['Pay amount','Working hours per week','Paid weeks per year'],examples:['25','40','52'],note:'Gross pay before deductions. Daily pay assumes five working days per week. No tax, benefits or overtime rules are applied.'}
};
export default function AdditionalCalculators({kind}:{kind:string}){return kind==='merit'?<Merit/>:<Calculator kind={kind}/>}
function Calculator({kind}:{kind:string}){
 const config=configs[kind],financial=['loan','savings','profit','salary'].includes(kind);
 const initial=()=>config.labels.map(()=>''),[values,setValues]=useState(initial),[currency,setCurrency]=useState('USD'),[period,setPeriod]=useState('hour'),[status,setStatus]=useState('');
 const change=(index:number,value:string)=>{setValues(previous=>previous.map((old,i)=>i===index?value:old));setStatus('')};
 const money=(value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency,currencyDisplay:'code',maximumFractionDigits:2}).format(value);
 let rows:{label:string;value:string}[]=[],error='',note='';const ready=values.every(value=>value.trim()!=='');
 try{if(ready){const n=values.map(number);
  if(kind==='marks'){const r=marksResult(n[0],n[1],n[2],n[3]);rows=[{label:'Current marks percentage',value:format(r.percentage)+'%'},{label:'Marks needed for your target',value:format(r.needed)+' / '+format(r.remaining)}];note=r.needed===0?'Your target is already covered by the marks obtained.':r.reachable?'The target is reachable with the remaining marks.':'This target is not reachable with the remaining marks.';}
  if(kind==='attendance'){const r=attendanceResult(n[0],n[1],n[2]);rows=[{label:'Current attendance',value:format(r.percentage)+'%'},{label:'Additional classes to attend',value:r.needed===null?'Not reachable':String(r.needed)},{label:'Classes you can miss at this target',value:String(r.canMiss)}];if(r.needed===null)note='After a missed class, a finite number of future classes cannot restore exactly 100% attendance.';}
  if(kind==='loan'){const r=loanResult(n[0],n[1],n[2]);rows=[{label:'Monthly payment',value:money(r.payment)},{label:'Total repayment',value:money(r.total)},{label:'Total interest',value:money(r.interest)}];}
  if(kind==='savings'){const r=savingsResult(n[0],n[1],n[2],n[3]);rows=[{label:'Projected balance',value:money(r.balance)},{label:'Your contributions',value:money(r.contributions)},{label:'Projected growth',value:money(r.interest)}];}
  if(kind==='profit'){const r=profitResult(n[0],n[1]);rows=[{label:r.profit<0?'Loss':'Profit',value:money(r.profit)},{label:'Profit margin',value:r.margin===null?'Not defined':format(r.margin)+'%'},{label:'Markup on cost',value:r.markup===null?'Not defined':format(r.markup)+'%'}];}
  if(kind==='salary'){const r=salaryResult(n[0],period,n[1],n[2]);rows=[{label:'Annual gross pay',value:money(r.annual)},{label:'Monthly equivalent',value:money(r.monthly)},{label:'Per paid week',value:money(r.weekly)},{label:'Hourly equivalent',value:money(r.hourly)}];}
 }}catch(failure){error=(failure as Error).message}
 return <>{financial&&<div className="input-grid"><div><label className="field-label" htmlFor="calc-currency">Display currency</label><select id="calc-currency" className="field-input" value={currency} onChange={e=>{setCurrency(e.target.value);setStatus('')}}>{['USD','EUR','GBP','PKR','INR','AED','CAD','AUD'].map(c=><option key={c}>{c}</option>)}</select></div>{kind==='salary'&&<div><label className="field-label" htmlFor="salary-period">Pay period</label><select id="salary-period" className="field-input" value={period} onChange={e=>{setPeriod(e.target.value);setStatus('')}}>{[['hour','Hourly'],['day','Daily'],['week','Weekly'],['month','Monthly'],['year','Annual']].map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>}</div>}
 <div className="input-grid">{config.labels.map((label,index)=><Field key={label} label={label} value={values[index]} placeholder={`e.g. ${config.examples[index]}`} onChange={value=>change(index,value)}/>)}</div>
 <div className="result-panel"><output aria-live="polite" aria-atomic="true">{!ready?<p>Enter values to calculate.</p>:error?<p className="error-message">{error}</p>:<><span className="result-label">Your result</span><strong className="result-value">{rows[0]?.value}</strong><p className="result-detail">{rows[0]?.label}</p><dl className="calculation-details">{rows.slice(1).map(row=><div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>)}</dl>{note&&<p className="small-note">{note}</p>}</>}</output></div>
 <div className="button-row">{ready&&!error&&rows.length>0&&<CopyButton text={rows.map(row=>row.label+': '+row.value).join('\n')} onStatus={setStatus}>Copy result</CopyButton>}<ResetButton onClick={()=>{setValues(initial());setCurrency('USD');setPeriod('hour');setStatus('')}}/></div><p role="status" className="small-note">{status||config.note}</p>{financial&&<p className="small-note">Currency changes only the label; there is no exchange conversion. Results are estimates based on your inputs.</p>}</>;
}
function Merit(){
 const initial=()=>['School','College','Admission test'].map((name,index)=>({id:index+1,name,earned:'',possible:'',weight:''}));
 const[rows,setRows]=useState(initial),[status,setStatus]=useState('');const ready=rows.every(row=>[row.earned,row.possible,row.weight].every(value=>value.trim()!==''));let value=0,error='';try{if(ready)value=meritResult(rows.map(row=>({earned:number(row.earned),possible:number(row.possible),weight:number(row.weight)})))}catch(failure){error=(failure as Error).message}
 const update=(id:number,key:string,value:string)=>{setRows(previous=>previous.map(row=>row.id===id?{...row,[key]:value}:row));setStatus('')};
 return <><p className="image-notice">Enter your component marks and the exact published weights of your institution. This is a custom aggregate calculator, not an official admission result.</p>{rows.map((row,index)=><section className="merit-component" key={row.id} aria-label={`Component ${index+1}`}><div className="merit-component-head"><label className="sr-only" htmlFor={`merit-name-${row.id}`}>Component {index+1} name</label><input className="field-input" id={`merit-name-${row.id}`} value={row.name} maxLength={60} onChange={e=>update(row.id,'name',e.target.value)}/><button className="remove-row" aria-label={`Remove component ${index+1}`} disabled={rows.length===1} onClick={()=>setRows(previous=>previous.filter(r=>r.id!==row.id))}><Trash2 size={15}/></button></div><div className="input-grid"><Field label={`Component ${index+1} obtained marks`} value={row.earned} onChange={v=>update(row.id,'earned',v)}/><Field label={`Component ${index+1} total marks`} value={row.possible} onChange={v=>update(row.id,'possible',v)}/><Field label={`Component ${index+1} weight (%)`} value={row.weight} onChange={v=>update(row.id,'weight',v)}/></div></section>)}<button className="outline-button" disabled={rows.length>=10} onClick={()=>setRows(previous=>[...previous,{id:Math.max(...previous.map(row=>row.id))+1,name:'New component',earned:'',possible:'',weight:''}])}><Plus size={15} className="inline-icon"/>Add component</button><div className="result-panel"><output aria-live="polite" aria-atomic="true"><span className="result-label">Weighted admission aggregate</span>{!ready?<p>Enter marks and weights to calculate.</p>:error?<p className="error-message">{error}</p>:<strong className="result-value">{format(value)}%</strong>}</output></div><div className="button-row">{ready&&!error&&<CopyButton text={`Admission aggregate: ${format(value)}%`} onStatus={setStatus}/>}<ResetButton onClick={()=>{setRows(initial());setStatus('')}}/></div><p className="small-note" role="status">{status||'Aggregate = sum of each marks percentage × its weight ÷ 100. Weights must total 100%. No admission thresholds are assumed.'}</p></>;
}
