'use client';
import {useRef,useState,type PointerEvent,type KeyboardEvent} from 'react';
import {adjustCrop,type CropHandle} from '@/tools/crop-selection';
import type {CropRect} from '@/tools/image-processing';
export function CropSurface({src,width,height,crop,disabled,onChange}:{src:string;width:number;height:number;crop:CropRect;disabled:boolean;onChange:(c:CropRect)=>void}){
 const[preview,setPreview]=useState<CropRect|null>(null),drag=useRef<{id:number;x:number;y:number;sx:number;sy:number;crop:CropRect;next:CropRect;handle:CropHandle}|null>(null);const c=preview||crop;
 function start(e:PointerEvent<HTMLDivElement>){if(disabled)return;const handle=(e.target as HTMLElement).closest<HTMLElement>('[data-handle]')?.dataset.handle as CropHandle|undefined;if(!handle)return;e.preventDefault();const r=e.currentTarget.getBoundingClientRect();drag.current={id:e.pointerId,x:e.clientX,y:e.clientY,sx:width/r.width,sy:height/r.height,crop,next:crop,handle};e.currentTarget.setPointerCapture(e.pointerId)}
 function move(e:PointerEvent<HTMLDivElement>){const d=drag.current;if(!d||d.id!==e.pointerId)return;d.next=adjustCrop(width,height,d.crop,(e.clientX-d.x)*d.sx,(e.clientY-d.y)*d.sy,d.handle);setPreview(d.next)}
 function end(e:PointerEvent<HTMLDivElement>,cancel=false){const d=drag.current;if(!d||d.id!==e.pointerId)return;drag.current=null;setPreview(null);if(!cancel)onChange(d.next);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)}
 function keys(e:KeyboardEvent,handle:CropHandle){const step=e.shiftKey?10:1,delta:{[key:string]:[number,number]}={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]};if(!delta[e.key])return;e.preventDefault();onChange(adjustCrop(width,height,crop,...delta[e.key],handle))}
 return <><div className="crop-surface" style={{aspectRatio:`${width}/${height}`}} onPointerDown={start} onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)}><img src={src} alt="Image with editable crop selection" width={width} height={height} draggable={false}/><div className="crop-live-selection" style={{left:`${c.x/width*100}%`,top:`${c.y/height*100}%`,width:`${c.width/width*100}%`,height:`${c.height/height*100}%`}}><button type="button" className="crop-move" data-handle="move" disabled={disabled} aria-label="Move crop selection" aria-describedby="crop-drag-help" onKeyDown={e=>keys(e,'move')}/>{(['nw','ne','sw','se'] as CropHandle[]).map((handle,i)=><button key={handle} type="button" className={`crop-handle crop-${handle}`} data-handle={handle} disabled={disabled} aria-label={`Resize crop ${['top left','top right','bottom left','bottom right'][i]}`} aria-describedby="crop-drag-help" onKeyDown={e=>keys(e,handle)}/>)}</div></div><p id="crop-drag-help" className="small-note">Drag the selection or its corners. Keyboard: focus a handle and use arrow keys; hold Shift for 10-pixel steps. Pixel fields remain available for precise edits.</p></>
}
