'use client';
import {useEffect,useLayoutEffect,useRef,useState,type KeyboardEvent} from 'react';
import {ChevronDown} from 'lucide-react';
import {toolCategories,availableTools,toolUrl} from '@/lib/tool-definitions';
import {SiteLink} from './site-link';
import {Icon} from './icon';
import {navs} from './navigation-data';
const menus=navs.map(n=>({...n,items:n.ids.flatMap(availableTools)}));
export default function DesktopNavigation({path}:{path:string}){
 const [open,setOpen]=useState<number|null>(null),[position,setPosition]=useState({left:0,top:0});const root=useRef<HTMLElement>(null),panel=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),hover=useRef(false),keyboardFocus=useRef<'first'|'last'|null>(null);
 const stopClose=()=>{if(timer.current)clearTimeout(timer.current)};const close=()=>{stopClose();setOpen(null)};
 useEffect(()=>()=>stopClose(),[]);
 useEffect(()=>{if(open===null)return;const outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(null)};document.addEventListener('pointerdown',outside);return()=>document.removeEventListener('pointerdown',outside)},[open]);
 useLayoutEffect(()=>{if(open===null)return;const trigger=root.current?.querySelectorAll<HTMLButtonElement>('.nav-trigger')[open];const place=()=>{if(!trigger)return;const r=trigger.getBoundingClientRect(),w=panel.current?.offsetWidth||360;setPosition({left:Math.max(16,Math.min(r.left,window.innerWidth-w-16)),top:r.bottom+12})};place();if(keyboardFocus.current){const links=panel.current?.querySelectorAll<HTMLAnchorElement>('a');(keyboardFocus.current==='last'?links?.[links.length-1]:links?.[0])?.focus();keyboardFocus.current=null}window.addEventListener('resize',place,{passive:true});return()=>window.removeEventListener('resize',place)},[open]);
 function keys(e:KeyboardEvent,index:number,inPanel=false){const triggers=root.current?.querySelectorAll<HTMLButtonElement>('.nav-trigger');if(e.key==='Escape'){e.preventDefault();close();triggers?.[index]?.focus()}else if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();const next=(index+(e.key==='ArrowRight'?1:menus.length-1))%menus.length;setOpen(next);triggers?.[next]?.focus()}else if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!inPanel){keyboardFocus.current=e.key==='ArrowUp'?'last':'first';if(open===index){const links=panel.current?.querySelectorAll<HTMLAnchorElement>('a');(e.key==='ArrowUp'?links?.[links.length-1]:links?.[0])?.focus();keyboardFocus.current=null}else setOpen(index)}else{const links=[...panel.current!.querySelectorAll<HTMLAnchorElement>('a')],at=links.indexOf(document.activeElement as HTMLAnchorElement);links[(at+(e.key==='ArrowDown'?1:links.length-1))%links.length]?.focus()}}}
 return <nav ref={root} className="desktop-navigation" aria-label="Main navigation" onPointerEnter={stopClose} onPointerLeave={()=>{stopClose();timer.current=setTimeout(()=>setOpen(null),160)}} onBlur={e=>{if(e.relatedTarget&&!e.currentTarget.contains(e.relatedTarget))close()}}><ul className="nav-list">{menus.map((n,i)=><li key={n.title}><button type="button" className={`nav-trigger ${n.ids.some(id=>path.startsWith('/'+id))?'active':''}`} aria-expanded={open===i} aria-controls={open===i?'desktop-tools-menu':undefined} onPointerEnter={e=>{if(e.pointerType==='mouse'){hover.current=true;setOpen(i)}}} onClick={()=>{stopClose();if(open===i&&hover.current){hover.current=false;return}hover.current=false;setOpen(open===i?null:i)}} onKeyDown={e=>keys(e,i)}>{n.title}<ChevronDown size={13} aria-hidden="true"/></button></li>)}</ul>{open!==null&&<div ref={panel} id="desktop-tools-menu" className={`nav-panel ${menus[open].items.length>4?'nav-panel-wide':''}`} style={{left:position.left,top:position.top}} onKeyDown={e=>keys(e,open,true)} onPointerEnter={stopClose}><div className="menu-heading"><span>{open===menus.length-1?'Generators & resources':toolCategories.find(c=>c.slug===menus[open].ids[0])!.name}</span><SiteLink href={`/${menus[open].ids[0]}/`}>View collection</SiteLink></div><div className={`menu-tool-list ${menus[open].items.length>4?'menu-two-columns':''}`} style={menus[open].items.length>4?{gridTemplateRows:`repeat(${Math.ceil(menus[open].items.length/2)},auto)`}:undefined}>{menus[open].items.map(t=><SiteLink key={t.id} href={toolUrl(t)} className="menu-tool" aria-current={path===toolUrl(t)?'page':undefined}><span className="menu-icon"><Icon name={t.icon}/></span><span>{t.name}<small>{t.description}</small></span></SiteLink>)}</div>{open===menus.length-1&&<div className="menu-resources"><SiteLink href="/blog/">Guides & articles</SiteLink><SiteLink href="/about/">About Tool Fera</SiteLink><SiteLink href="/contact/">Help & contact</SiteLink></div>}</div>}</nav>
}
