'use client';
import {useRef,useState} from 'react';
import {generateUUIDs,convertColor,type ConvertedColor} from '@/tools/developer-utils';
import {ActionButton,CopyButton,ResetButton,SuccessNote} from './action-button';
import {useActionSequence} from './use-action-sequence';
export default function DeveloperExtraTools({kind}:{kind:'uuid'|'color'}){return kind==='uuid'?<UUIDTool/>:<ColorTool/>}
function UUIDTool(){
 const [count,setCount]=useState('1'),[output,setOutput]=useState(''),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const revision=useRef(0),sequence=useActionSequence();
 const clear=()=>{revision.current++;sequence.cancel();setBusy(false);setOutput('');setError('');setStatus('')};
 async function generate(){if(busy)return;clear();const id=revision.current,clock=sequence.begin();setBusy(true);try{const value=generateUUIDs(Number(count)).join('\n');await clock.finish();if(id!==revision.current)return;setOutput(value);setStatus('UUIDs generated on your device.')}catch(e){if(id===revision.current)setError((e as Error).message)}finally{if(id===revision.current)setBusy(false)}}
 return <><label className="field-label" htmlFor="uuid-count">Number of UUIDs</label><input id="uuid-count" className="field-input" type="number" min="1" max="100" step="1" value={count} onChange={e=>{clear();setCount(e.target.value)}}/><p className="small-note">Version 4 · cryptographically random · up to 100 per batch.</p><div className="button-row"><ActionButton busy={busy} busyLabel="Generating UUIDs…" completed={!!output} motion="generate" onClick={()=>void generate()}>Generate UUIDs</ActionButton><ResetButton onClick={()=>{clear();setCount('1')}}>Reset</ResetButton></div>{output&&<><label className="field-label" htmlFor="uuid-output">Generated UUIDs</label><textarea id="uuid-output" className="tool-textarea monospace" rows={Math.min(10,Number(count)+1)} readOnly value={output}/><div className="button-row"><CopyButton text={output} onStatus={setStatus}>Copy UUIDs</CopyButton><ResetButton onClick={clear}>Clear result</ResetButton></div></>}{error&&<p className="error-message" role="alert">{error}</p>}<p role="status" className="image-status">{status}</p></>
}
function ColorTool(){
 const [input,setInput]=useState('#2f5bff'),[output,setOutput]=useState<ConvertedColor|null>(null),[error,setError]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);
 const revision=useRef(0),sequence=useActionSequence();
 const clear=()=>{revision.current++;sequence.cancel();setBusy(false);setOutput(null);setError('');setStatus('')};
 async function convert(){if(busy)return;clear();const id=revision.current,clock=sequence.begin();setBusy(true);try{const value=convertColor(input);await clock.finish();if(id!==revision.current)return;setOutput(value);setStatus('Color values ready.')}catch(e){if(id===revision.current)setError((e as Error).message)}finally{if(id===revision.current)setBusy(false)}}
 return <><label className="field-label" htmlFor="color-input">HEX, RGB or HSL color</label><input id="color-input" className="field-input monospace" value={input} maxLength={200} spellCheck={false} onChange={e=>{clear();setInput(e.target.value)}} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();void convert()}}}/><p className="small-note">Accepts short/long HEX, RGB percentages, HSL degrees and optional alpha. Named colors and CSS variables are not supported.</p><div className="button-row"><ActionButton busy={busy} busyLabel="Converting…" completed={!!output} motion="convert" onClick={()=>void convert()}>Convert color</ActionButton><ResetButton onClick={()=>{clear();setInput('#2f5bff')}}>Reset</ResetButton><ResetButton onClick={()=>{clear();setInput('')}}>Clear</ResetButton></div>{output&&<><SuccessNote>Color converted.</SuccessNote><div className="color-output"><div className="color-swatch" aria-label={`Color preview ${output.hex}`} style={{background:output.rgb}}/>{(['hex','rgb','hsl'] as const).map(format=><div className="color-format" key={format}><span>{format.toUpperCase()}</span><code>{output[format]}</code><CopyButton text={output[format]} onStatus={setStatus}>Copy {format.toUpperCase()}</CopyButton></div>)}</div></>}{error&&<p role="alert" className="error-message">{error}</p>}<p role="status" className="image-status">{status}</p></>
}
