'use client';
import {useId,useRef,useState,useEffect,type Ref} from 'react';
import {Upload,FileCheck2,ScanLine} from 'lucide-react';
import {validateFileSelection,friendlyFileError,readableBytes,type FileLimits,type ReadProgress,type ReadReporter} from '@/tools/file-input';
export function FileDropZone({label,title,description,accept,multiple=false,disabled=false,busy=false,selected=false,status,error,inputRef,onFiles,limits,existingFiles=[],resetKey=0}:{label:string;title:string;description:string;accept:string;multiple?:boolean;disabled?:boolean;busy?:boolean;selected?:boolean;status?:string;error?:string;inputRef?:Ref<HTMLInputElement>;limits?:FileLimits|(()=>FileLimits);existingFiles?:File[];resetKey?:number;onFiles:(files:File[],report:ReadReporter)=>void|Promise<void>}){
 // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydration enables the native picker; disabling it also clears the external drag session.
 const id=useId(),depth=useRef(0),locked=useRef(false),alive=useRef(true);const[hydrated,setHydrated]=useState(false),[drag,setDrag]=useState(false),[localError,setLocalError]=useState(''),[reading,setReading]=useState(false),[progress,setProgress]=useState<ReadProgress|null>(null);useEffect(()=>{alive.current=true;setHydrated(true);return()=>{alive.current=false}},[]);const unavailable=disabled||reading||!hydrated;useEffect(()=>{if(unavailable){depth.current=0;setDrag(false)}},[unavailable]);
 const intakeRun=useRef(0);useEffect(()=>{if(busy)return;intakeRun.current++;locked.current=false;setLocalError('');setReading(false);setProgress(null)},[resetKey]);
 async function receive(files:File[]){
  if(unavailable||locked.current||!files.length)return;
  setLocalError('');setProgress(null);
  try{validateFileSelection([...existingFiles,...files],{maxFiles:multiple?20:1,...(typeof limits==='function'?limits():limits)})}catch(e){setLocalError(friendlyFileError(e));return}
  locked.current=true;setReading(true);const run=++intakeRun.current;
  try{await onFiles(files,p=>{if(alive.current&&run===intakeRun.current)setProgress(p)})}catch(e){if(alive.current&&run===intakeRun.current)setLocalError(friendlyFileError(e))}finally{if(run===intakeRun.current){locked.current=false;if(alive.current){setReading(false);setProgress(null)}}}
 }
 const issue=localError||error,preparing=busy||reading;
 return <div className="file-input-group"><label htmlFor={id} className={`upload-area file-dropzone ${drag?'is-dragging':''} ${selected?'has-files':''} ${preparing?'is-preparing':''} ${issue?'has-error':''}`} aria-disabled={unavailable} aria-busy={preparing||!hydrated} data-state={issue?'error':drag?'drag-over':preparing?status?.startsWith('Reading')?'reading':'analyzing':selected?'ready':'idle'} onDragEnter={e=>{e.preventDefault();if(!unavailable){depth.current++;setDrag(true)}}} onDragOver={e=>e.preventDefault()} onDragLeave={e=>{e.preventDefault();depth.current=Math.max(0,depth.current-1);if(!depth.current)setDrag(false)}} onDrop={e=>{e.preventDefault();depth.current=0;setDrag(false);void receive(Array.from(e.dataTransfer.files))}}><span className={`upload-icon ${preparing?'upload-scanning':''}`}>{preparing?<ScanLine size={25}/>:selected?<FileCheck2 size={25}/>:<Upload size={25}/>}</span><strong>{!hydrated?'Preparing file picker…':preparing?(status||'Reading and validating…'):drag?'Release to add your file':title}</strong><span>{description}</span>{preparing&&<span className="upload-scan-line" aria-hidden="true"/>}<span className="upload-browse">{selected?'Change or add files':'Browse files'}</span><input id={id} ref={inputRef} type="file" aria-label={label} aria-invalid={!!issue} aria-describedby={issue?id+'-error':undefined} accept={accept} multiple={multiple} disabled={unavailable} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';void receive(files)}}/></label>
 {issue&&<p id={id+'-error'} className="error-message file-validation-error" role="alert">{issue}</p>}
 {preparing&&!issue&&<div className="file-read-progress" role="status" aria-live="polite"><div><span>{progress&&progress.loaded<progress.total?'Reading file…':status||'Validating file…'}</span>{progress&&<strong>{Math.round(progress.loaded/Math.max(1,progress.total)*100)}%</strong>}</div><progress max={progress?.total||1} value={progress?.loaded} aria-label="Local file reading progress"/>{progress&&<small>{readableBytes(progress.loaded)} / {readableBytes(progress.total)}{progress.count&&progress.count>1?` · file ${progress.index} of ${progress.count}`:''}</small>}</div>}
 </div>
}
