import {SiteLink as Link} from './site-link';
import {ShieldCheck,SlidersHorizontal,GraduationCap,Braces} from 'lucide-react';
import {categories,getTool,availableTools,popularIds,toolUrl,homeFAQ} from '@/lib/catalog';
import {JsonLd,site} from '@/lib/seo';
import {ToolCard,CategoryCard,SectionHeading,FAQAccordion} from './primitives';
import {ToolSearch} from './search';
import {SavedTools} from './saved-tools';
import {HeroPhrases} from './hero-phrases';
export function HomePage(){return <main id="main">
 <JsonLd data={{'@context':'https://schema.org','@graph':[{'@type':'WebSite','@id':site.origin+'/#website',name:site.name,url:site.origin+'/',description:site.description},{'@type':'Organization','@id':site.origin+'/#organization',name:site.name,url:site.origin+'/'}]}}/>
 <section className="hero"><div className="hero-grid" aria-hidden="true"/><div className="container hero-layout"><div className="hero-content"><span className="hero-eyebrow">The everyday digital toolkit</span><h1>Less friction.<br/>More <span>finished.</span></h1><HeroPhrases/><p className="hero-description">Compress PDFs, turn PDF into DOCX or Word into PDF.<br className="desktop-break"/> Resize and compress images, format JSON, and calculate in seconds.</p><div className="hero-search"><ToolSearch/></div><div className="quick-searches"><span>Try</span>{['pdf-merger','image-compressor','json-formatter'].map(id=>{const t=getTool(id)!;return <Link key={id} href={toolUrl(t)}>{t.name}</Link>})}</div></div><div className="hero-art"><img src="/images/toolfera-workflows-1200.webp" srcSet="/images/toolfera-workflows-640.webp 640w, /images/toolfera-workflows-1200.webp 1200w" sizes="(max-width: 760px) 90vw, 46vw" width={1200} height={922} fetchPriority="high" decoding="async" alt="Tool Fera workflows: PDF Compressor, PDF to DOCX, Image Resizer, JSON, Words and Calculator"/></div></div></section>
 <section className="container section popular-section"><SectionHeading title="The tools you’ll reach for." description="Ready to use, right in your browser." href="#categories" link="Explore collections"/><div className="editorial-tools">{popularIds.map((id,i)=><ToolCard key={id} tool={getTool(id)!} variant={i===0?'featured':'medium'}/>)}</div></section>
 <SavedTools/>
 <section className="category-section" id="categories"><div className="container section"><SectionHeading title="What are you working on?" description="One collection for each kind of task."/><div className="category-grid">{categories.map(c=><CategoryCard key={c.slug} category={c}/>)}</div></div></section>
 <section className="student-section"><div className="container student-layout"><div className="student-copy"><span className="eyebrow">Student tools</span><h2>Your grades.<br/><span>The bigger picture.</span></h2><p>Calculate a credit-weighted semester GPA, combine semesters into a CGPA, or turn marks into a percentage.</p><Link className="light-button" href="/student-tools/">Explore student tools</Link></div><div className="student-workbench"><div className="student-workbench-head"><GraduationCap size={23}/><span>Academic toolkit</span></div>{availableTools('student-tools').map((t,i)=><Link href={toolUrl(t)} key={t.id} className="student-tool"><span className="student-index">0{i+1}</span><span><h3>{t.name}</h3><p>{t.description}</p></span><span className="student-tool-open">Open</span></Link>)}<p className="student-note">Use your institution’s grade-point and credit rules.</p></div></div></section>
 <section className="container section trust-section"><div className="trust-intro"><h2>Your work stays <br/>on your device.</h2><Link className="text-link" href="/blog/browser-tools-and-privacy/">How browser processing works</Link></div><div className="trust-details">{[{icon:ShieldCheck,title:'Local processing',text:'Your files, text and calculations are processed here on your device.'},{icon:SlidersHorizontal,title:'Inputs you can check',text:'Choose your units and settings. Check the result before using it.'},{icon:Braces,title:'Only tool names are remembered',text:'History keeps tool IDs, never your files, text or passwords.'}].map(x=><article key={x.title}><x.icon size={21}/><div><h3>{x.title}</h3><p>{x.text}</p></div></article>)}</div></section>
 <section className="faq-section"><div className="container faq-layout"><div><h2>A few useful answers.</h2><Link className="text-link" href="/contact/">Help & contact</Link></div><FAQAccordion items={homeFAQ}/></div></section>
 </main>}
