'use client';
import {useActionSequence} from './use-action-sequence';
import {useEffect,useRef,useState} from 'react';
import {createImageProcessor,type ImageProcessor} from '@/tools/image-client';
import {fileSize,type ImageMetadata} from '@/tools/image-processing';
import {FileDropZone} from './file-dropzone';
import {useFileFeedback} from './use-file-feedback';
import {friendlyFileError,validatePDF,type ReadReporter} from '@/tools/file-input';
import {ActionButton,CopyButton,ResetButton,SuccessNote} from './action-button';
import {AnimatedDownloadButton} from './animated-download-button';
export default function ImageOCRTool(){const sequence=useActionSequence(),intake=useFileFeedback();const[file,setFile]=useState<File|null>(null),[meta,setMeta]=useState<ImageMetadata|null>(null),[busy,setBusy]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<{text:string;confidence:number;url:string;docxUrl:string}|null>(null),[preview,setPreview]=useState('');const processor=useRef<ImageProcessor|null>(null),job=useRef<AbortController|null>(null),version=useRef(0),urls=useRef<string[]>([]);const clear=()=>{urls.current.forEach(URL.revokeObjectURL);urls.current=[];setResult(null);setPreview('')};const reset=()=>{intake.reset();sequence.cancel();version.current++;job.current?.abort();processor.current?.dispose();processor.current=null;clear();intake.clear();setFile(null);setMeta(null);setBusy(false);setStatus('');setError('')};useEffect(()=>()=>{version.current++;job.current?.abort();processor.current?.dispose();urls.current.forEach(URL.revokeObjectURL)},[]);
 async function choose(files:File[],read?:ReadReporter){if(busy||!files[0])return;reset();const f=files[0],id=++version.current;setBusy(true);setStatus('Reading image…');try{const mobile=window.matchMedia('(max-width:767px)').matches;if(f.size>(mobile?5:10)*1048576)throw new Error(`Choose an image up to ${mobile?5:10} MB for OCR.`);const bytes=new Uint8Array(await f.slice(0,12).arrayBuffer());if(!(bytes[0]===255&&bytes[1]===216)&&!(bytes[0]===137&&bytes[1]===80))throw new Error('Choose a valid PNG or JPEG image for OCR.');const p=await createImageProcessor();if(id!==version.current){p.dispose();return}processor.current=p;const info=await p.inspect(f,read);if(id!==version.current)return;if(info.width*info.height>(mobile?12000000:20000000))throw new Error(`OCR input is limited to ${mobile?12:20} million pixels. Resize the image first.`);setFile(f);setMeta(info);const url=URL.createObjectURL(f);urls.current.push(url);setPreview(url);setStatus('Image ready for English OCR.')}catch(e){if(id===version.current){processor.current?.dispose();processor.current=null;intake.fail(e);setStatus('')}}finally{if(id===version.current)setBusy(false)}}
 async function run(){
  if(!file||!meta||busy)return;const id=++version.current,clock=sequence.begin(),controller=new AbortController();job.current=controller;
  if(result){URL.revokeObjectURL(result.url);URL.revokeObjectURL(result.docxUrl);urls.current=urls.current.filter(url=>url!==result.url&&url!==result.docxUrl)}setResult(null);setBusy(true);setError('');setStatus('Preparing image for OCR…');
  try{
   let owned=processor.current;if(!owned){owned=await createImageProcessor();if(id!==version.current){owned.dispose();return}processor.current=owned;await owned.inspect(file);if(id!==version.current)return}
   const cap=window.matchMedia('(max-width:767px)').matches?1800000:3000000,scale=Math.min(1,Math.sqrt(cap/(meta.width*meta.height)));
   const image=await owned.process({width:Math.max(1,Math.floor(meta.width*scale)),height:Math.max(1,Math.floor(meta.height*scale)),mode:'fit',mime:'image/png',quality:100});owned.dispose();if(processor.current===owned)processor.current=null;if(id!==version.current)return;
   const {recognizeImage}=await import('@/tools/image-ocr');if(id!==version.current)return;
   const output=await recognizeImage(new Uint8Array(await image.blob.arrayBuffer()),controller.signal,message=>{if(id===version.current)setStatus(message)});const {runWord}=await import('@/tools/word-client');if(id!==version.current)return;const docx=await runWord('build',{document:output.document},controller.signal,message=>{if(id===version.current)setStatus(message)});await clock.finish();if(id!==version.current)return;
   const blob=new Blob([output.text],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob);const docxUrl=URL.createObjectURL(docx);urls.current.push(url,docxUrl);setResult({...output,url,docxUrl});setStatus('Text extracted. Review spelling and numbers.');
  }catch(e){if(id===version.current){processor.current?.dispose();processor.current=null;setError(friendlyFileError(e));setStatus('')}}finally{if(id===version.current)setBusy(false)}
 }

 return <><FileDropZone label="Choose OCR image" title={file?file.name:'Drop an image with text here'} description={meta?`${meta.width} × ${meta.height} px · ${fileSize(meta.bytes)}`:'PNG or JPEG · English text · processed on your device'} accept="image/png,image/jpeg,.png,.jpg,.jpeg" limits={()=>({maxFileBytes:(window.matchMedia('(max-width:767px)').matches?5:10)*1048576})} disabled={busy} busy={busy&&!meta} selected={!!file} status={status} error={intake.error} resetKey={intake.resetKey} onFiles={(f,read)=>choose(f,read)}/><p className="small-note">English printed text works best. Crop excess background and use a clear, upright photo. OCR can misread names, numbers and handwriting.</p><div className="button-row"><ActionButton motion="ocr" disabled={!file} busy={busy} busyLabel="Recognizing…" completed={!!result} onClick={()=>void run()}>Extract text</ActionButton><ResetButton onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div><p className="image-status" role="status">{status}</p>{error&&<p className="error-message" role="alert">{error}</p>}{preview&&<figure className="ocr-image-preview"><img src={preview} width={meta?.width} height={meta?.height} alt="Selected image for English OCR"/></figure>}{result&&<><SuccessNote>Readable text extracted.</SuccessNote>{result.confidence<70&&<p className="image-notice">Low recognition confidence. Check the text carefully.</p>}<label className="field-label" htmlFor="ocr-text">Recognized text</label><textarea id="ocr-text" className="tool-textarea" rows={10} readOnly value={result.text}/><div className="button-row"><CopyButton text={result.text} onStatus={setStatus}>Copy text</CopyButton><AnimatedDownloadButton href={result.url} download={(file?.name.replace(/\.[^.]+$/,'')||'recognized-text')+'.txt'}>Download text</AnimatedDownloadButton><AnimatedDownloadButton href={result.docxUrl} download={(file?.name.replace(/\.[^.]+$/,'')||'recognized-text')+'.docx'}>Download Word File</AnimatedDownloadButton></div></>}<p className="small-note">Mobile: 5 MB / 12 million input pixels. Desktop: 10 MB / 20 million pixels. OCR preparation is capped at 1.8 / 3 million pixels, with sensible upscaling for small text and contrast correction when useful. English assets load only when you extract text. Files are never uploaded.</p></>
}
