'use client';
import {AnimatedDownloadButton} from './animated-download-button';
import {useActionSequence} from './use-action-sequence';
import {ACTION_VISUAL_MS,COMPRESS_VISUAL_MS} from '@/tools/action-sequence';
import {useEffect,useRef,useState} from 'react';
import {LockKeyhole,UnlockKeyhole,Image as ImageIcon} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {FileDropZone} from './file-dropzone';
import {useFileFeedback} from './use-file-feedback';
import {friendlyFileError,validatePDF,type ReadReporter} from '@/tools/file-input';
import {CropSurface} from './crop-surface';
import {ActionButton,SuccessNote,ResetButton} from './action-button';
import {createImageProcessor,type ImageProcessor} from '@/tools/image-client';
import {dimensions,validateCrop,fileSize,formatLabel,imageFormats,type ImageMetadata,type ResizeMode} from '@/tools/image-processing';
type Result=ImageMetadata&{url:string};
const inputTypes='image/jpeg,image/png,image/webp,image/avif,image/bmp,image/gif';
async function inputMime(file:File){const b=new Uint8Array(await file.slice(0,32).arrayBuffer()),ascii=new TextDecoder().decode(b);if(b[0]===255&&b[1]===216)return 'image/jpeg';if(b[0]===137&&ascii.slice(1,4)==='PNG')return 'image/png';if(ascii.startsWith('RIFF')&&ascii.slice(8,12)==='WEBP')return 'image/webp';if(ascii.startsWith('GIF8'))return 'image/gif';if(ascii.startsWith('BM'))return 'image/bmp';if(ascii.slice(4,8)==='ftyp'&&/avif|avis/.test(ascii))return 'image/avif';throw new Error('Choose JPEG, PNG, WebP, AVIF, BMP or GIF. HEIC and TIFF are not supported by this version.');}
export default function ImageTool({mode='resize',initialFormat}:{mode?:'resize'|'compress'|'convert'|'crop';initialFormat?:string}){
 const sequence=useActionSequence(),intake=useFileFeedback();
 const input=useRef<HTMLInputElement>(null),processor=useRef<ImageProcessor|null>(null),generation=useRef(0),sourceURL=useRef(''),resultURL=useRef('');
 const [epoch,setEpoch]=useState(0),[ready,setReady]=useState(false),[formats,setFormats]=useState<string[]>([]),[compatibility,setCompatibility]=useState(false),[busy,setBusy]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState('');
 const [file,setFile]=useState<File|null>(null),[meta,setMeta]=useState<ImageMetadata|null>(null),[original,setOriginal]=useState(''),[result,setResult]=useState<Result|null>(null);
 const [cropX,setCropX]=useState('0'),[cropY,setCropY]=useState('0');
 const [width,setWidth]=useState('1200'),[height,setHeight]=useState('800'),[maxWidth,setMaxWidth]=useState(''),[locked,setLocked]=useState(true),[resizeMode,setResizeMode]=useState<ResizeMode>('fit'),[preset,setPreset]=useState('original'),[format,setFormat]=useState(initialFormat||(mode==='compress'?'image/jpeg':mode==='convert'?'image/png':'keep')),[quality,setQuality]=useState(80);
 useEffect(()=>{let cancelled=false;createImageProcessor().then(p=>{if(cancelled){p.dispose();return}processor.current=p;setFormats(p.formats);setCompatibility(p.compatibility);setReady(true)}).catch(()=>{if(!cancelled)intake.fail(new Error('Unable to start image processing. Reset this tool to try again.'))});return()=>{cancelled=true;processor.current?.dispose();processor.current=null}},[epoch]);
 useEffect(()=>()=>{generation.current++;if(sourceURL.current)URL.revokeObjectURL(sourceURL.current);if(resultURL.current)URL.revokeObjectURL(resultURL.current)},[]);
 function clearResult(){if(resultURL.current)URL.revokeObjectURL(resultURL.current);resultURL.current='';setResult(null);setError('')}
 function reset(){intake.reset();setReady(false);sequence.cancel();generation.current++;clearResult();intake.clear();if(sourceURL.current)URL.revokeObjectURL(sourceURL.current);sourceURL.current='';setOriginal('');setFile(null);setMeta(null);setBusy(false);setWidth('1200');setHeight('800');setCropX('0');setCropY('0');setMaxWidth('');setLocked(true);setResizeMode('fit');setPreset('original');setFormat(initialFormat||(mode==='compress'?'image/jpeg':mode==='convert'?'image/png':'keep'));setQuality(80);if(input.current)input.current.value='';processor.current?.dispose();processor.current=null;setEpoch(v=>v+1)}
 async function choose(candidate:File|null,read?:ReadReporter){if(!candidate||busy||!processor.current)return;generation.current++;const current=generation.current;clearResult();intake.clear();if(sourceURL.current)URL.revokeObjectURL(sourceURL.current);sourceURL.current='';setOriginal('');setFile(null);setMeta(null);setBusy(true);setPhase('Reading file…');try{if(candidate.size>20*1048576)throw new Error('Choose a file no larger than 20 MB.');const mime=await inputMime(candidate);const f=new File([candidate],candidate.name,{type:mime});setPhase('Preparing image…');const info=await processor.current.inspect(f,read);if(current!==generation.current)return;sourceURL.current=URL.createObjectURL(f);setOriginal(sourceURL.current);setFile(f);setMeta(info);setWidth(String(info.width));setHeight(String(info.height));setCropX('0');setCropY('0');setMaxWidth('');setPreset('original');setLocked(true);setResizeMode('fit');if(format==='keep'&&!formats.includes(info.mime))setFormat('image/png');}catch(e){if(current===generation.current)intake.fail(e)}finally{if(current===generation.current)setBusy(false)}}
 const mime=format==='keep'?meta?.mime||'image/png':format;
 const meaningfulQuality=['image/jpeg','image/webp','image/avif'].includes(mime);
 function changeDimension(value:string,which:'width'|'height'){clearResult();setPreset('custom');if(which==='width'){setWidth(value);if(locked&&meta&&Number(value)>0)setHeight(String(Math.max(1,Math.round(Number(value)*meta.height/meta.width))))}else{setHeight(value);if(locked&&meta&&Number(value)>0)setWidth(String(Math.max(1,Math.round(Number(value)*meta.width/meta.height))))}}
 function choosePreset(value:string){clearResult();setPreset(value);if(value==='custom')return;if(value==='original'&&meta){setWidth(String(meta.width));setHeight(String(meta.height));setLocked(true);setResizeMode('fit')}else{const [w,h]=value.split('x');setWidth(w);setHeight(h);setLocked(false);setResizeMode('fit')}}
 function target(){if(!meta)throw new Error('Choose an image first.');if(mode==='crop'){const crop=validateCrop(meta.width,meta.height,{x:Number(cropX),y:Number(cropY),width:Number(width),height:Number(height)});return {width:crop.width,height:crop.height,mode:'stretch' as const,crop}}if(mode==='convert')return {width:meta.width,height:meta.height,mode:'fit' as const};if(mode==='compress'){const w=maxWidth===''?meta.width:Math.min(Number(maxWidth),meta.width);if(!Number.isInteger(w)||w<1)throw new Error('Enter a whole-number maximum width, or leave it empty.');return {width:w,height:Math.max(1,Math.round(meta.height*w/meta.width)),mode:'fit' as const}}return {width:Number(width),height:Number(height),mode:resizeMode}}
 let intended:{width:number;height:number}|undefined;try{if(meta){const t=target();intended=dimensions(meta.width,meta.height,t.width,t.height,t.mode)}}catch{}
 async function process(){if(!file||!meta||!processor.current)return;clearResult();const current=++generation.current;const clock=sequence.begin();setBusy(true);setPhase('Processing image…');try{const t=target();dimensions(meta.width,meta.height,t.width,t.height,t.mode);if(!formats.includes(mime))throw new Error('Choose an output format supported by this browser.');const out=await processor.current.process({...t,mime,quality});await clock.finish(mode==='compress'?COMPRESS_VISUAL_MS:ACTION_VISUAL_MS);if(current!==generation.current)return;resultURL.current=URL.createObjectURL(out.blob);setResult({url:resultURL.current,width:out.width,height:out.height,bytes:out.bytes,mime:out.mime})}catch(e){if(current===generation.current)setError(friendlyFileError(e))}finally{if(current===generation.current)setBusy(false)}}
 const savings=meta&&result?meta.bytes-result.bytes:0;
 const percent=meta&&result?Math.abs(savings/meta.bytes*100).toFixed(1):'0';
 const action=mode==='crop'?'Crop image':mode==='compress'?'Compress image':mode==='convert'?'Convert image':'Resize image';
 return <div className="image-tool"><FileDropZone status={phase} error={intake.error} resetKey={intake.resetKey} inputRef={input} label="Choose image file" title={file?file.name:'Drop an image here'} description={meta?`${formatLabel(meta.mime)} · ${fileSize(meta.bytes)} · ${meta.width} × ${meta.height} px`:'JPEG, PNG, WebP, AVIF, BMP or GIF · up to 20 MB'} accept={inputTypes} disabled={busy||!ready} busy={busy&&!meta} selected={!!file} onFiles={(files,read)=>choose(files[0]||null,read)}/>{file&&<div className="file-selection-actions"><button className="text-link" disabled={busy} onClick={reset}>Remove image</button><span>Original file stays unchanged</span></div>}
 {!ready&&!intake.error&&<p className="small-note" role="status">Preparing the image processor…</p>}
 {meta&&<dl className="image-metadata"><div><dt>Original dimensions</dt><dd>{meta.width.toLocaleString()} × {meta.height.toLocaleString()} px</dd></div><div><dt>Format</dt><dd>{formatLabel(meta.mime)}</dd></div><div><dt>File size</dt><dd>{fileSize(meta.bytes)}</dd></div></dl>}
 {meta?.mime==='image/gif'&&<p className="image-notice">GIF input uses its first frame. Animation is not preserved.</p>}
 <div className="image-settings">
 {mode==='resize'&&<><label className="field-label" htmlFor="image-preset">Resize preset</label><select id="image-preset" className="field-input" value={preset} disabled={busy||!meta} onChange={e=>choosePreset(e.target.value)}><option value="original">Original dimensions</option>{['1920x1080','1280x720','1080x1080','1080x1350'].map(x=><option value={x} key={x}>{x.replace('x',' × ')}</option>)}<option value="custom">Custom</option></select><div className="image-dimensions"><div><label className="field-label" htmlFor="image-width">Width (px)</label><input className="field-input" id="image-width" type="number" min={1} max={8000} step={1} value={width} disabled={busy||!meta} onChange={e=>changeDimension(e.target.value,'width')}/></div><span className="dimension-cross" aria-hidden="true">×</span><div><label className="field-label" htmlFor="image-height">Height (px)</label><input className="field-input" id="image-height" type="number" min={1} max={8000} step={1} value={height} disabled={busy||!meta} onChange={e=>changeDimension(e.target.value,'height')}/></div></div><label className={`aspect-control ${locked?'is-locked':''}`} htmlFor="aspect-lock"><span>{locked?<LockKeyhole size={17}/>:<UnlockKeyhole size={17}/>}<span>Lock aspect ratio<small>{locked?'On · dimensions stay proportional':'Off · set dimensions independently'}</small></span></span><Switch id="aspect-lock" aria-label="Lock aspect ratio" checked={locked} disabled={busy||!meta} onCheckedChange={v=>{clearResult();setLocked(v);if(v&&meta){setHeight(String(Math.max(1,Math.round(Number(width)*meta.height/meta.width))));setResizeMode('fit')}}}/></label><label className="field-label" htmlFor="image-mode">Resize behavior</label><select id="image-mode" className="field-input" value={resizeMode} disabled={busy||!meta} onChange={e=>{clearResult();setResizeMode(e.target.value as ResizeMode)}}><option value="fit">Fit — preserve proportions</option><option value="fill">Fill — crop to dimensions</option><option value="stretch">Stretch — use exact dimensions</option></select><p className="small-note">Fit stays inside the selected dimensions. Fill crops from the center. Stretch can distort the image.</p></>}
 {mode==='crop'&&<><label className="field-label" htmlFor="crop-preset">Crop selection</label><select id="crop-preset" className="field-input" disabled={busy||!meta} value={preset} onChange={e=>{if(!meta)return;clearResult();setPreset(e.target.value);if(e.target.value==='custom')return;const ratio=e.target.value==='square'?1:e.target.value==='wide'?16/9:e.target.value==='photo'?4/3:meta.width/meta.height;const w=Math.min(meta.width,Math.floor(meta.height*ratio)),h=Math.min(meta.height,Math.round(w/ratio));setWidth(String(w));setHeight(String(h));setCropX(String(Math.floor((meta.width-w)/2)));setCropY(String(Math.floor((meta.height-h)/2)))}}><option value="original">Full image</option><option value="square">Square · 1:1</option><option value="wide">Wide · 16:9</option><option value="photo">Photo · 4:3</option><option value="custom">Custom selection</option></select><div className="crop-fields">{([{id:'crop-x',label:'Left (px)',value:cropX,set:setCropX},{id:'crop-y',label:'Top (px)',value:cropY,set:setCropY},{id:'crop-width',label:'Crop width (px)',value:width,set:setWidth},{id:'crop-height',label:'Crop height (px)',value:height,set:setHeight}]).map(f=><div key={f.id}><label className="field-label" htmlFor={f.id}>{f.label}</label><input id={f.id} className="field-input" type="number" step={1} min={f.id==='crop-x'||f.id==='crop-y'?0:1} value={f.value} disabled={busy||!meta} onChange={e=>{clearResult();setPreset('custom');f.set(e.target.value)}}/></div>)}</div><p className="small-note">Set the selection in original image pixels. The highlighted preview shows exactly what will be kept; output has no padding or resizing.</p>{meta&&original&&intended&&<CropSurface src={original} width={meta.width} height={meta.height} crop={{x:Number(cropX),y:Number(cropY),width:Number(width),height:Number(height)}} disabled={busy} onChange={c=>{clearResult();setPreset('custom');setCropX(String(c.x));setCropY(String(c.y));setWidth(String(c.width));setHeight(String(c.height))}}/>}</>}
 {mode==='compress'&&<details className="pdf-compression-advanced"><summary>Advanced settings</summary><div><label className="field-label" htmlFor="image-max-width">Maximum width (optional)</label><input className="field-input" id="image-max-width" type="number" min={1} max={8000} step={1} placeholder={meta?`Keep original: ${meta.width} px`:'Keep original dimensions'} value={maxWidth} disabled={busy} onChange={e=>{clearResult();setMaxWidth(e.target.value)}}/><p className="small-note">A smaller width can save more space. The compressor never enlarges your image.</p></div></details>}
 <label className="field-label" htmlFor="image-format">Output format</label><select id="image-format" className="field-input" value={format} disabled={busy||!ready} onChange={e=>{clearResult();setFormat(e.target.value)}}>{mode!=='convert'&&<option value="keep" disabled={!!meta&&!formats.includes(meta.mime)}>Keep original format</option>}{imageFormats.filter(f=>formats.includes(f.mime)).map(f=><option value={f.mime} key={f.mime}>{f.label}{f.mime==='image/bmp'?' · uncompressed':''}</option>)}</select>
 {meaningfulQuality&&<details className="pdf-compression-advanced"><summary>Advanced quality settings</summary><div className="slider-field"><div className="slider-label"><label id="image-quality">{formatLabel(mime)} quality</label><strong>{quality}%</strong></div><Slider min={10} max={100} step={5} value={[quality]} disabled={busy} onValueChange={v=>{clearResult();setQuality(v[0])}} aria-labelledby="image-quality"/></div></details>}
 {meta&&intended&&<p className="image-output-summary"><ImageIcon size={15}/>{intended.width.toLocaleString()} × {intended.height.toLocaleString()} px<span>{formatLabel(mime)}</span></p>}
 <p className="small-note">JPEG and BMP use white for transparency. PNG, WebP and AVIF can retain it. AVIF export appears only when this browser supports it.</p>
 </div>
 <div className="button-row"><ActionButton disabled={!meta||!ready} busy={busy} busyLabel={mode==='resize'?'Resizing…':mode==='crop'?'Cropping…':'Converting…'} completed={!!result} onClick={()=>void process()}>{action}</ActionButton><ResetButton className="outline-button" onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div>
 <p className="image-status" role="status" aria-live="polite">{busy?phase:''}</p>
 {error&&<p className="error-message" role="alert">{error}</p>}{result&&<SuccessNote>{mode==='compress'&&savings<=0?'Image processed. This copy is not smaller; keep your original or choose a lower quality.':mode==='crop'?'Image cropped successfully.':mode==='compress'?'Image compressed successfully.':mode==='convert'?'Conversion complete.':'Image resized successfully.'}</SuccessNote>}
 {meta&&result&&<div className={`image-savings ${savings<=0?'no-reduction':''}`} role="status"><div><span>{savings>0?'File size reduced':savings<0?'Output is larger':'File size unchanged'}</span><strong>{percent}% {savings>0?'smaller':savings<0?'larger':'change'}</strong></div><p>{savings>0?`${fileSize(savings)} saved`:savings<0?'Try lower quality, smaller dimensions or a different format.':'Compare the preview before downloading.'}<small>{fileSize(meta.bytes)} → {fileSize(result.bytes)}</small></p></div>}
 {meta&&original&&<div className={`image-comparison ${result?'has-result':''}`}><figure><div className="preview-surface"><img src={original} alt="Original selected image" width={meta.width} height={meta.height} decoding="async"/></div><figcaption><strong>Original</strong><span>{meta.width} × {meta.height} · {formatLabel(meta.mime)} · {fileSize(meta.bytes)}</span></figcaption></figure>{result&&<figure><div className="preview-surface"><img src={result.url} alt="Processed image preview" width={result.width} height={result.height} decoding="async"/></div><figcaption><strong>{mode==='compress'?'Compressed':'Result'}</strong><span>{result.width} × {result.height} · {formatLabel(result.mime)} · {fileSize(result.bytes)}</span></figcaption></figure>}</div>}
 {result&&file&&<AnimatedDownloadButton className="primary-button image-download" href={result.url} download={`toolfera-${file.name.replace(/\.[^.]+$/,'')}.${imageFormats.find(f=>f.mime===result.mime)?.ext||'png'}`}>Download {formatLabel(result.mime)}</AnimatedDownloadButton>}
 <p className="small-note processing-note">{compatibility?'Compatibility processing: 4 million pixels maximum.':'Image work runs in a background worker on this device.'} Original files stay unchanged. Output: up to 16 million pixels and 8,000 px per side. HEIC/TIFF and animated export are not supported.</p>
 </div>
}
