import {ArrowRight,FileText,Image,Code2,Type,Calculator,GraduationCap,Sparkles,ShieldCheck,Check,Layers,RotateCcw,Smartphone,MessageSquare} from 'lucide-react';
import {SiteLink as Link} from './site-link';
import {ResourceLayout,ResourceCTA,ResourceLink} from './resource-layout';
import {information,legalContent} from '@/lib/information-content';
export {information} from '@/lib/information-content';

const collections=[
 {href:'/pdf-tools/',title:'PDFs & documents',description:'Merge pages, compress files and convert PDF or Word documents.',icon:<FileText/>},
 {href:'/image-tools/',title:'Images & OCR',description:'Resize, crop, convert and extract printed text from images.',icon:<Image/>},
 {href:'/text-tools/',title:'Text & writing',description:'Count, clean and organize words, characters and lines.',icon:<Type/>},
 {href:'/finance-tools/',title:'Everyday calculations',description:'Work through percentages, repayments, savings and journey costs.',icon:<Calculator/>},
 {href:'/student-tools/',title:'Student tasks',description:'Understand GPA, CGPA, marks, attendance and merit calculations.',icon:<GraduationCap/>},
 {href:'/developer-tools/',title:'Developer utilities',description:'Format JSON, encode text, create IDs and convert colors.',icon:<Code2/>},
 {href:'/generators/',title:'Useful generators',description:'Create QR codes, passwords, random numbers and simple invoices.',icon:<Sparkles/>}
];
function About(){return <ResourceLayout name="About" path="/about/" eyebrow="A LITTLE LESS FRICTION" title="Everyday work. A clearer way through." description="Tool Fera brings practical browser utilities together, so a file to prepare, a number to check or a piece of text to tidy is easier to finish.">
 <section className="resource-introduction"><div><span className="eyebrow">WHAT TOOL FERA IS</span><h2>A toolkit for the small jobs that matter.</h2></div><div><p>Combine documents. Make an image fit. Turn printed text into something you can work with. Check a calculation or clean up JSON. Tool Fera covers everyday file, writing, student and developer tasks in one place.</p><p>Open the tool you need, follow a short workflow and review a clear result. There is no Tool Fera account to create or subscription to choose.</p></div></section>
 <section className="resource-section" aria-labelledby="about-collections"><div className="resource-section-heading"><span className="eyebrow">WHAT YOU CAN DO</span><h2 id="about-collections">Different tasks. One familiar toolkit.</h2><p>Choose a collection and find the utility that fits your work.</p></div><nav className="resource-collections" aria-label="Tool collections">{collections.map(item=><ResourceLink key={item.href} {...item}/>)}</nav></section>
 <section className="resource-section" aria-labelledby="about-principles"><div className="resource-section-heading"><span className="eyebrow">HOW WE APPROACH IT</span><h2 id="about-principles">Simple inputs. Results you can check.</h2></div><div className="resource-principles"><article><span className="resource-icon"><Check aria-hidden="true"/></span><h3>Useful defaults</h3><p>Start with a sensible setting. Choose more control when you need it, without making every task technical.</p></article><article><span className="resource-icon"><ShieldCheck aria-hidden="true"/></span><h3>Content stays close</h3><p>The current processing tools run on your device. Website and engine assets still load over the network; each tool explains its processing and limits.</p><Link className="text-link" href="/privacy-policy/">How data is handled</Link></article><article><span className="resource-icon"><Layers aria-hidden="true"/></span><h3>Clear tradeoffs</h3><p>Compare actual file sizes, check recognized text and review converted pages. A tool should show what changed, not promise a perfect result.</p></article></div></section>
 <section className="resource-story"><div><span className="eyebrow">WHY IT EXISTS</span><h2>Small tasks should not interrupt the whole day.</h2></div><div><p>Everyday work often needs several little utilities. Tool Fera brings those workflows into a consistent place, with instructions that make the next step clear.</p><p>The interface supports desktop and mobile use. Processing speed depends on your device, browser and file size; larger documents and OCR can take longer. Keep important originals and review outputs before relying on them. The <Link href="/blog/">practical guides</Link> explain compression trade-offs, grade weighting and other common decisions without promising perfect results.</p></div></section><ResourceCTA/>
 </ResourceLayout>}
function Help(){return <ResourceLayout name="Help & contact" path="/contact/" eyebrow="LET’S GET YOU UNSTUCK" title="A little help. A clear next step." description="Start with the tool’s instructions, then use these checks for file errors, browser limits or an unexpected result.">
 <aside className="resource-callout" aria-labelledby="contact-availability"><MessageSquare aria-hidden="true"/><div><h2 id="contact-availability">Current contact availability</h2><p>Tool Fera currently has no public support email or submission form. This page provides self-help guidance; it does not send bug reports, feedback or tool suggestions.</p></div></aside>
 <section className="resource-section" aria-labelledby="help-common"><div className="resource-section-heading"><span className="eyebrow">START HERE</span><h2 id="help-common">Common problems, practical checks.</h2></div><div className="help-grid"><article><span className="resource-icon"><FileText aria-hidden="true"/></span><h3>A file will not open</h3><p>Check its actual format and the size/page limit shown by the tool. A renamed file extension does not convert the file. Try an unencrypted PDF or a supported DOCX, JPG or PNG where the tool requests it.</p><Link className="text-link" href="/pdf-tools/">See PDF tool requirements</Link></article><article><span className="resource-icon"><Layers aria-hidden="true"/></span><h3>Processing stops or takes longer</h3><p>Large files and OCR use device memory. Try fewer pages or smaller images, keep the tab open and avoid running several large jobs together. Some tools load their engine on first use.</p><Link className="text-link" href="/blog/browser-tools-and-privacy/">Understand browser processing</Link></article><article><span className="resource-icon"><RotateCcw aria-hidden="true"/></span><h3>The result looks different</h3><p>Check quality, page size, fitting, units and tool-specific settings. Review conversion and OCR output against the original. Cancel or reset before choosing the file again; save anything you need first.</p><Link className="text-link" href="/disclaimer/">Review result limitations</Link></article><article><span className="resource-icon"><Smartphone aria-hidden="true"/></span><h3>You are using a phone</h3><p>Use a current browser and keep the page in the foreground during processing. Start with a smaller file if memory is limited. Downloads are managed by your browser; check its downloads list or your device’s files app.</p><Link className="text-link" href="/#categories">Choose a tool</Link></article></div></section>
 <section className="resource-help-next" aria-labelledby="help-next"><h2 id="help-next">Looking for something else?</h2><div><article><h3>A bug or unexpected output</h3><p>Keep the tool name, browser version, error message and non-sensitive steps that reproduce the issue. This site currently has no channel to submit them. Avoid sharing confidential source files or passwords.</p></article><article><h3>Feedback or a tool suggestion</h3><p>Note the task you want to complete, the expected result and where the current workflow falls short. Feedback submission is not available on the site yet.</p></article><article><h3>Privacy or legal information</h3><p>Read the <Link href="/privacy-policy/">Privacy Policy</Link> for file and storage handling, and the <Link href="/terms-of-use/">Terms of Use</Link> for responsible use. No separate privacy submission channel is currently provided.</p></article><article><h3>Favorites or history</h3><p>Use “Clear favorites & history” on the homepage, or remove site data in browser settings. Those lists contain tool IDs, not your files or calculations, and belong to the current browser profile.</p></article></div></section><ResourceCTA title="The tool page is your first guide." description="Each working tool includes its own inputs, limits and instructions. Find the one you need and check those details before retrying."/>
 </ResourceLayout>}
function Legal({slug}:{slug:string}){const model=legalContent[slug],meta=information[slug];return <ResourceLayout name={meta.title} path={`/${slug}/`} eyebrow="CLEAR INFORMATION, PLAIN LANGUAGE" title={meta.title} description={model.intro} legal>
 <div className="legal-layout"><nav className="legal-toc" aria-label="On this page"><h2>On this page</h2><ol>{model.sections.map((section,i)=><li key={section.id}><Link href={`#${section.id}`}><span>{String(i+1).padStart(2,'0')}</span>{section.title}</Link></li>)}</ol><div className="legal-related"><Link href="/privacy-policy/">Privacy Policy</Link><Link href="/terms-of-use/">Terms of Use</Link><Link href="/disclaimer/">Disclaimer</Link><Link href="/contact/">Help & contact</Link></div></nav><article className="legal-article"><aside className="resource-callout"><ShieldCheck aria-hidden="true"/><div><h2>{model.callout.title}</h2><p>{model.callout.text}</p></div></aside>{model.sections.map((section,i)=><section id={section.id} className="legal-section" key={section.id}><span className="legal-section-number" aria-hidden="true">{String(i+1).padStart(2,'0')}</span><h2>{section.title}</h2>{section.paragraphs.map(p=><p key={p}>{p}</p>)}</section>)}<footer className="legal-article-footer"><p>Continue with <Link href="/contact/">Help & contact</Link>, or explore the <Link href="/blog/">Guides & articles</Link>.</p><Link className="text-link" href="#main">Back to top<ArrowRight size={14} aria-hidden="true"/></Link></footer></article></div>
 </ResourceLayout>}
export function InformationPage({slug}:{slug:string}){return slug==='about'?<About/>:slug==='contact'?<Help/>:<Legal slug={slug}/>}
