'use client';
import {AnimatedDownloadButton} from './animated-download-button';
import {useActionSequence} from './use-action-sequence';
import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {FileText,ChevronUp,ChevronDown,X,GripVertical} from 'lucide-react';
import {fileSize} from '@/tools/image-processing';
import {runPDF} from '@/tools/pdf-client';
import {FileDropZone} from './file-dropzone';
import {useFileFeedback} from './use-file-feedback';
import {friendlyFileError,validatePDF,type ReadReporter} from '@/tools/file-input';
import {ActionButton,SuccessNote,ResetButton} from './action-button';
export type PDFMode='merge'|'split'|'rotate'|'delete'|'reorder';
export default function PDFTool({mode='merge'}:{mode?:PDFMode}){
 const sequence=useActionSequence(),intake=useFileFeedback();
 const merge=mode==='merge';const[files,Files]=useState<File[]>([]),[counts,Counts]=useState<number[]>([]),[pages,Pages]=useState('1'),[angle,Angle]=useState('90'),[busy,Busy]=useState(false),[status,Status]=useState(''),[error,Error]=useState(''),[result,Result]=useState<{url:string;bytes:number;pages:number}|null>(null);
 const input=useRef<HTMLInputElement>(null),job=useRef<AbortController|null>(null),url=useRef(''),generation=useRef(0),dragIndex=useRef<number|null>(null);
 const pointerSort=useRef<{from:number;startY:number;target:number;moved:boolean}|null>(null);const[sorting,Sorting]=useState<number|null>(null);
 function startSort(e:PointerEvent<HTMLSpanElement>,i:number){if(busy)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);pointerSort.current={from:i,startY:e.clientY,target:i,moved:false};Sorting(i)}
 function trackSort(e:PointerEvent<HTMLSpanElement>){const p=pointerSort.current;if(!p)return;p.moved ||= Math.abs(e.clientY-p.startY)>8;const rows=Array.from(e.currentTarget.closest('ol')!.querySelectorAll('li'));let distance=Infinity;rows.forEach((row,i)=>{const r=row.getBoundingClientRect(),d=Math.abs(e.clientY-r.top-r.height/2);if(d<distance){distance=d;p.target=i}})}
 function finishSort(){const p=pointerSort.current;pointerSort.current=null;Sorting(null);if(p?.moved)move(p.from,p.target)}
 useEffect(()=>()=>{generation.current++;job.current?.abort();if(url.current)URL.revokeObjectURL(url.current)},[]);
 function clear(){if(url.current)URL.revokeObjectURL(url.current);url.current='';Result(null);Error('');Status('')}
 function reset(){intake.reset();sequence.cancel();generation.current++;job.current?.abort();job.current=null;clear();Files([]);Counts([]);Pages('1');Busy(false);if(input.current)input.current.value=''}
 async function choose(selected:File[],read?:ReadReporter){if(busy||!selected.length)return;clear();intake.clear();const next=merge?[...files,...selected]:selected.slice(0,1),id=++generation.current;job.current=new AbortController();Busy(true);Status('Reading files…');try{for(const f of next)await validatePDF(f);const inspected=await runPDF('inspect',next,{},Status,job.current.signal,read);if(id!==generation.current)return;Files(next);Counts(inspected.counts!);const n=inspected.counts![0];Pages(mode==='delete'?'1':n>1?`1-${n}`:'1');Status('Ready to process.')}catch(e){if(id===generation.current)intake.fail(e)}finally{if(id===generation.current)Busy(false)}}
 function move(i:number,j:number){if(i===j||busy)return;clear();intake.clear();const next=[...files],nextCounts=[...counts];const[f]=next.splice(i,1),[c]=nextCounts.splice(i,1);next.splice(j,0,f);nextCounts.splice(j,0,c);Files(next);Counts(nextCounts)}
 async function process(){const clock=sequence.begin();clear();const id=++generation.current;job.current=new AbortController();Busy(true);try{const out=await runPDF(mode,files,{pages,angle:Number(angle)},Status,job.current.signal);await clock.finish();if(id!==generation.current)return;url.current=URL.createObjectURL(out.blob);Result({url:url.current,bytes:out.blob.size,pages:out.pages});Status('')}catch(e){if(id===generation.current)Error(friendlyFileError(e))}finally{if(id===generation.current)Busy(false)}}
 const action=({merge:'Merge PDFs',split:'Extract pages',rotate:'Rotate pages',delete:'Delete pages',reorder:'Reorder pages'})[mode];
 return <div className="pdf-tool"><FileDropZone status={status} error={intake.error} resetKey={intake.resetKey} inputRef={input} label={merge?'Choose PDF files':'Choose PDF file'} title={merge?'Drop PDFs here':'Drop a PDF here'} description={merge?'Add more PDFs · up to 10 files · 20 MB each, 40 MB total':'PDF · up to 20 MB · up to 500 pages'} accept="application/pdf,.pdf" multiple={merge} limits={{maxFiles:merge?10:1}} existingFiles={merge?files:[]} disabled={busy} busy={busy&&!files.length} selected={!!files.length} onFiles={(f,read)=>choose(f,read)}/>
 {files.length>0&&<ol className="pdf-file-list">{files.map((f,i)=><li key={`${f.name}-${i}`} className={sorting===i?'is-sorting':undefined} draggable={merge&&!busy} onDragStart={e=>{dragIndex.current=i;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i))}} onDragEnd={()=>{dragIndex.current=null}} onDragOver={e=>{if(merge)e.preventDefault()}} onDrop={e=>{e.preventDefault();if(dragIndex.current!==null)move(dragIndex.current,i);dragIndex.current=null}}><span className="pdf-order">{i+1}</span>{merge?<span className="pdf-drag-handle" aria-hidden="true" onPointerDown={e=>startSort(e,i)} onPointerMove={trackSort} onPointerUp={finishSort} onPointerCancel={()=>{pointerSort.current=null;Sorting(null)}}><GripVertical size={16}/></span>:<FileText size={19}/>}<span><strong>{f.name}</strong><small>PDF · {counts[i]} pages · {fileSize(f.size)}</small></span>{merge&&<div><button aria-label={`Move document ${i+1} up`} disabled={busy||i===0} onClick={()=>move(i,i-1)}><ChevronUp size={17}/></button><button aria-label={`Move document ${i+1} down`} disabled={busy||i===files.length-1} onClick={()=>move(i,i+1)}><ChevronDown size={17}/></button></div>}<button aria-label={`Remove document ${i+1}`} disabled={busy} onClick={()=>{clear();Files(files.filter((_,n)=>n!==i));Counts(counts.filter((_,n)=>n!==i))}}><X size={17}/></button></li>)}</ol>}
 {!merge&&<><label className="field-label" htmlFor="pdf-pages">{mode==='delete'?'Pages to delete':mode==='reorder'?'New page order':mode==='rotate'?'Pages to rotate':'Pages to extract'}</label><input id="pdf-pages" className="field-input" placeholder="1, 3-5, 8" value={pages} disabled={busy||!files.length} onChange={e=>{clear();Pages(e.target.value)}}/><p className="small-note">{mode==='delete'?'Selected pages are removed. Keep at least one page.':mode==='reorder'?'Include every page exactly once, in your desired order.':'Enter page numbers or ranges. Page numbers start at 1.'}</p></>}
 {mode==='rotate'&&<><label className="field-label" htmlFor="pdf-angle">Clockwise rotation</label><select id="pdf-angle" className="field-input" value={angle} disabled={busy} onChange={e=>{clear();Angle(e.target.value)}}><option value="90">90°</option><option value="180">180°</option><option value="270">270°</option></select></>}
 {merge&&files.length>0&&<p className="small-note">Drag files to reorder, or use the up/down buttons. Add more files using Browse above.</p>}
 <div className="button-row"><ActionButton disabled={merge?files.length<2:!files.length} busy={busy} busyLabel={mode==='merge'?'Merging…':mode==='rotate'?'Rotating…':'Processing…'} completed={!!result} onClick={()=>void process()}>{action}</ActionButton><ResetButton className="outline-button" onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div><p className="image-status" role="status">{busy?status:''}</p>{error&&<p className="error-message" role="alert">{error}</p>}
 {result&&<><SuccessNote>PDF {mode==='merge'?'merged':mode==='split'?'extracted':mode==='rotate'?'rotated':mode==='delete'?'updated':'reordered'} successfully.</SuccessNote><div className="result-panel"><span className="result-label">Your new document</span><strong className="pdf-result">{result.pages} pages · {fileSize(result.bytes)}</strong><div className="button-row"><AnimatedDownloadButton className="primary-button" href={result.url} download={`toolfera-${mode}.pdf`}>Download PDF</AnimatedDownloadButton></div></div></>}
 <p className="small-note">Up to 500 output pages. Encrypted PDFs are unsupported. Review the output: forms, bookmarks and signatures may not carry over. Files stay on your device.</p></div>
}
