'use client';
import {AnimatedDownloadButton} from './animated-download-button';
import {useActionSequence} from './use-action-sequence';
import {ACTION_VISUAL_MS,COMPRESS_VISUAL_MS} from '@/tools/action-sequence';
import {useEffect,useRef,useState} from 'react';
import {X} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {fileSize} from '@/tools/image-processing';
import {runPDF} from '@/tools/pdf-client';
import {FileDropZone} from './file-dropzone';
import {useFileFeedback} from './use-file-feedback';
import {friendlyFileError,validatePDF,type ReadReporter} from '@/tools/file-input';
import {ActionButton,SuccessNote,ResetButton} from './action-button';
export default function PDFRasterTool({compress=false}:{compress?:boolean}){
 const sequence=useActionSequence(),intake=useFileFeedback();
 const[file,FileState]=useState<File|null>(null),[count,Count]=useState(0),[pages,Pages]=useState(''),[method,Method]=useState('lossless'),[dpi,DPI]=useState('144'),[mime,Mime]=useState<'image/jpeg'|'image/png'>('image/jpeg'),[quality,Quality]=useState(75),[busy,Busy]=useState(false),[status,Status]=useState(''),[error,Error]=useState(''),[result,Result]=useState<{url:string;bytes:number;pages:number;images:{url:string;name:string;bytes:number}[]}|null>(null);
 const controller=useRef<AbortController|null>(null),version=useRef(0),urls=useRef<string[]>([]);
 const clear=()=>{urls.current.forEach(URL.revokeObjectURL);urls.current=[];Result(null);Error('');Status('')};
 const reset=()=>{intake.reset();sequence.cancel();version.current++;controller.current?.abort();clear();FileState(null);Count(0);Pages('');Busy(false)};
 useEffect(()=>()=>{version.current++;controller.current?.abort();urls.current.forEach(URL.revokeObjectURL)},[]);
 async function choose(files:File[],read?:ReadReporter){const f=files[0];if(!f||busy)return;clear();intake.clear();FileState(null);Count(0);const id=++version.current;controller.current=new AbortController();Busy(true);Status('Reading PDF…');try{if(f.size>20*1048576)throw new globalThis.Error('Choose a PDF up to 20 MB.');await validatePDF(f);const r=await runPDF('inspect',[f],{},Status,controller.current.signal,read);if(id!==version.current)return;FileState(f);Count(r.counts![0]);Pages('')}catch(e){if(id===version.current)intake.fail(e)}finally{if(id===version.current)Busy(false)}}
 async function process(){if(!file)return;const clock=sequence.begin();clear();intake.clear();const id=++version.current;controller.current=new AbortController();Busy(true);try{let out,images:{url:string;name:string;bytes:number}[]=[];if(compress&&method==='lossless')out=await runPDF('compress',[file],{},Status,controller.current.signal);else{Status('Preparing PDF renderer…');const {rasterPDF}=await import('@/tools/pdf-raster');const rendered=await rasterPDF(file,{pages:compress?undefined:pages,dpi:Number(dpi),mime:compress?'image/jpeg':mime,quality,signal:controller.current.signal,progress:Status});if(id!==version.current)return;if(compress)out=await runPDF('images',rendered.files,{dimensions:rendered.dimensions,margin:0},Status,controller.current.signal);else{out=await runPDF('zip',rendered.files,{},Status,controller.current.signal);images=rendered.files.map(f=>{const url=URL.createObjectURL(f);urls.current.push(url);return{url,name:f.name,bytes:f.size}})}}await clock.finish(compress?COMPRESS_VISUAL_MS:ACTION_VISUAL_MS);if(id!==version.current)return;const url=URL.createObjectURL(out.blob);urls.current.push(url);Result({url,bytes:out.blob.size,pages:out.pages,images});Status('')}catch(e){if(id===version.current){Error(friendlyFileError(e,'Unable to render this PDF. Try a valid unencrypted document or fewer pages.'))}}finally{if(id===version.current)Busy(false)}}
 const change=()=>{clear()};const delta=file&&result?file.size-result.bytes:0;
 return <><FileDropZone status={status} error={intake.error} resetKey={intake.resetKey} label="Choose PDF file" title={file?file.name:'Drop a PDF here'} description={file?`PDF · ${count} pages · ${fileSize(file.size)}`:'PDF · up to 20 MB · files stay on your device'} accept="application/pdf,.pdf" disabled={busy} busy={busy&&!file} selected={!!file} onFiles={(f,read)=>choose(f,read)}/>{file&&<div className="file-selection-actions"><button className="text-link" disabled={busy} onClick={reset}><X size={13}/>Remove PDF</button><span>{count} pages · {fileSize(file.size)}</span></div>}
 {compress?<><label className="field-label" htmlFor="pdf-compression">Compression method</label><select id="pdf-compression" className="field-input" disabled={busy} value={method} onChange={e=>{change();Method(e.target.value)}}><option value="lossless">Lossless · optimize PDF structure</option><option value="raster">Image-based · reduce quality, remove searchable text</option></select><p className="small-note">{method==='lossless'?'Rewrites compressed object streams without lowering image quality. Existing optimized PDFs may not shrink. Digital signatures become invalid.':'Every page becomes a JPEG image. Searchable text, selectable text, links, forms and accessibility tags are removed. Use this for scans only when that tradeoff is acceptable.'}</p></>:<><label className="field-label" htmlFor="render-pages">Pages to export (optional)</label><input id="render-pages" className="field-input" disabled={busy} placeholder="All pages, or 1, 3-5" value={pages} onChange={e=>{change();Pages(e.target.value)}}/><label className="field-label" htmlFor="render-format">Image format</label><select id="render-format" className="field-input" disabled={busy} value={mime} onChange={e=>{change();Mime(e.target.value as typeof mime)}}><option value="image/jpeg">JPG</option><option value="image/png">PNG</option></select></>}
 {(!compress||method==='raster')&&<details className="pdf-compression-advanced"><summary>Advanced settings</summary><div><label className="field-label" htmlFor="render-dpi">Resolution</label><select id="render-dpi" className="field-input" disabled={busy} value={dpi} onChange={e=>{change();DPI(e.target.value)}}><option value="96">96 DPI · smaller</option><option value="144">144 DPI · balanced</option><option value="192">192 DPI · sharper</option></select>{(compress||mime==='image/jpeg')&&<div className="slider-field"><div className="slider-label"><label id="pdf-jpeg-quality">JPEG quality</label><strong>{quality}%</strong></div><Slider min={30} max={95} step={5} disabled={busy} value={[quality]} onValueChange={v=>{change();Quality(v[0])}} aria-labelledby="pdf-jpeg-quality"/></div>}<p className="small-note">Up to 40 rendered pages, 6 million pixels per page and 40 MB output. Lower resolution uses less memory.</p></div></details>}
 <div className="button-row"><ActionButton disabled={!file} busy={busy} busyLabel="Converting…" completed={!!result} onClick={()=>void process()}>{compress?'Compress PDF':'Convert to images'}</ActionButton><ResetButton className="outline-button" onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div><p className="image-status" role="status">{busy?status:''}</p>{error&&<p className="error-message" role="alert">{error}</p>}
 {result&&<><SuccessNote>{compress?'PDF optimization complete.':'PDF pages converted successfully.'}</SuccessNote><div className="result-panel"><span className="result-label">{compress?'Output PDF':'Page images in a ZIP'}</span><strong className="pdf-result">{result.pages} pages · {fileSize(result.bytes)}</strong>{compress&&file&&<p>{delta>0?`${(delta/file.size*100).toFixed(1)}% smaller · ${fileSize(delta)} saved`:delta<0?'Output is larger. Keep the original or try a different setting.':'File size unchanged.'}</p>}<div className="button-row"><AnimatedDownloadButton className="primary-button" href={result.url} download={compress?'toolfera-compressed.pdf':'toolfera-pages.zip'}>{compress?'Download PDF':'Download ZIP'}</AnimatedDownloadButton></div></div>{result.images.length>0&&<div className="pdf-image-results">{result.images.map(f=><figure key={f.name}><img src={f.url} alt={`Rendered ${f.name}`} loading="lazy"/><figcaption><span>{f.name} · {fileSize(f.bytes)}</span><AnimatedDownloadButton href={f.url} download={f.name} className="outline-button">Download image</AnimatedDownloadButton></figcaption></figure>)}</div>}</>}
 <p className="small-note">Original files stay unchanged. Encrypted PDFs are unsupported. All processing uses local open-source libraries; no paid API or server upload.</p></>
}
