import {SiteLink as Link} from './site-link';
import {ChevronRight,Plus} from 'lucide-react';
import {categories,categoryTools,availableTools,toolUrl,type Category,type Tool,type FAQ} from '@/lib/catalog';
import {BreadcrumbSchema} from '@/lib/seo';
import {Icon} from './icon';
import {FavoriteButton} from './saved-tools-store';
export {Logo} from './logo';
export function ToolCard({tool,variant='standard'}:{tool:Tool;variant?:'standard'|'featured'|'medium'|'compact'}){return <article className={`tool-card tool-card-${variant}`}><FavoriteButton id={tool.id} name={tool.name}/><Link className="tool-card-link" href={toolUrl(tool)}><div className="card-top"><span className="tool-icon"><Icon name={tool.id in {'gpa-calculator':1,'cgpa-calculator':1,'percentage-calculator':1}?tool.id:tool.icon}/></span><span className="card-category">{categories.find(c=>c.slug===tool.category)?.name}</span></div><div className="card-copy"><h3>{tool.name}</h3><p>{tool.description}</p></div><div className="card-bottom"><span className="card-open">{!tool.kind?'View details':'Open tool'}</span></div></Link></article>}
export function CategoryCard({category}:{category:Category}){const ts=categoryTools(category.slug),ready=availableTools(category.slug);return <Link className={`category-card category-${category.slug}`} href={`/${category.slug}/`}><div className="category-top"><Icon name={category.icon}/></div><span className="category-motif" aria-hidden="true">{({'pdf-tools':'PDF','image-tools':'W × H','student-tools':'3.75','finance-tools':'% =','text-tools':'Aa','developer-tools':'{ }','generators':'••••'} as Record<string,string>)[category.slug]}</span><h3>{category.name}</h3><p>{category.short}</p><div className="category-examples">{(ready.length?ready:ts).slice(0,3).map(t=><span key={t.id}>{t.name}</span>)}</div><div className="category-bottom"><span className="category-open">Browse collection</span></div></Link>}
export function FAQAccordion({items}:{items:FAQ[]}){return <><div className="faq-list">{items.map(x=><details className="faq-item" key={x.question}><summary>{x.question}<Plus size={18} aria-hidden="true"/></summary><p>{x.answer}</p></details>)}</div></>}
export function Breadcrumbs({items}:{items:{name:string;url:string}[]}){return <><BreadcrumbSchema items={items}/><nav className="breadcrumbs" aria-label="Breadcrumb"><ol>{items.map((x,i)=><li key={x.url}>{i>0&&<ChevronRight size={13} aria-hidden="true"/>}{i===items.length-1?<span aria-current="page">{x.name}</span>:<Link href={x.url}>{x.name}</Link>}</li>)}</ol></nav></>}
export function SectionHeading({eyebrow,title,description,href,link}:{eyebrow?:string;title:string;description?:string;href?:string;link?:string}){return <div className="section-heading"><div>{eyebrow&&<span className="eyebrow">{eyebrow}</span>}<h2>{title}</h2>{description&&<p>{description}</p>}</div>{href&&<Link className="text-link" href={href}>{link||'Explore tools'}</Link>}</div>}
