'use client';
import {AnimatedDownloadButton} from './animated-download-button';
import {useActionSequence} from './use-action-sequence';
import {useState,useRef,useEffect} from 'react';
import {ActionButton,SuccessNote,ResetButton} from './action-button';
export default function QRTool(){
 const sequence=useActionSequence();
 const[text,Text]=useState(''),[size,Size]=useState('512'),[busy,Busy]=useState(false),[error,Error]=useState(''),[result,Result]=useState<{png:string;svg:string}|null>(null);const revision=useRef(0),svgURL=useRef('');
 function clear(){sequence.cancel();revision.current++;if(svgURL.current)URL.revokeObjectURL(svgURL.current);svgURL.current='';Result(null);Error('');Busy(false)}useEffect(()=>()=>{revision.current++;if(svgURL.current)URL.revokeObjectURL(svgURL.current)},[]);
 async function generate(){clear();const clock=sequence.begin();const id=revision.current;try{if(!text.trim())throw new globalThis.Error('Enter a link or some text.');if(new TextEncoder().encode(text).length>1800)throw new globalThis.Error('Use at most 1,800 UTF-8 bytes. Shorter text makes an easier-to-scan code.');Busy(true);const QRCode=(await import('qrcode')).default;const options={width:Number(size),margin:4,errorCorrectionLevel:'M' as const,color:{dark:'#15223aff',light:'#ffffffff'}};const [png,svg]=await Promise.all([QRCode.toDataURL(text,options),QRCode.toString(text,{...options,type:'svg'})]);await clock.finish();if(id!==revision.current)return;svgURL.current=URL.createObjectURL(new Blob([svg],{type:'image/svg+xml'}));Result({png,svg:svgURL.current})}catch(e){if(id===revision.current)Error(e instanceof globalThis.Error?e.message:'Unable to create this code. Try shorter text.')}finally{if(id===revision.current)Busy(false)}}
 return <><label className="field-label" htmlFor="qr-text">Link or text</label><textarea className="tool-textarea" id="qr-text" value={text} maxLength={1800} placeholder="https://example.com, or the text you want to share" onChange={e=>{clear();Text(e.target.value)}}/><label className="field-label" htmlFor="qr-size">PNG size</label><select className="field-input" id="qr-size" value={size} onChange={e=>{clear();Size(e.target.value)}}><option value="256">256 × 256 px</option><option value="512">512 × 512 px</option><option value="1024">1024 × 1024 px</option></select><div className="button-row"><ActionButton busy={busy} busyLabel="Generating…" completed={!!result} onClick={()=>void generate()}>Generate QR code</ActionButton><ResetButton onClick={()=>{clear();Text('')}}>Reset</ResetButton></div>{error&&<p role="alert" className="error-message">{error}</p>}{result&&<><SuccessNote>QR code ready. Scan it to check the content.</SuccessNote><div className="qr-preview"><img src={result.png} width={Number(size)} height={Number(size)} alt="Generated QR code"/></div><div className="button-row"><AnimatedDownloadButton className="primary-button" href={result.png} download="toolfera-qr.png">Download PNG</AnimatedDownloadButton><AnimatedDownloadButton className="outline-button" href={result.svg} download="toolfera-qr.svg">Download SVG</AnimatedDownloadButton></div></>}<p className="small-note">Static QR code · four-module quiet zone · medium error correction. No redirect service, tracking or expiry is added. Text stays on your device.</p></>
}
