'use client';
import {useEffect,useRef,useState} from 'react';
import {Switch} from '@/components/ui/switch';
import {randomNumbers} from '@/tools/random-numbers';
import {useActionSequence} from './use-action-sequence';
import {ActionButton,CopyButton,ResetButton,SuccessNote} from './action-button';
import {AnimatedDownloadButton} from './animated-download-button';
export default function RandomNumberTool(){
 const[values,setValues]=useState(['1','100','1']),[unique,setUnique]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<{text:string;url:string}|null>(null),[status,setStatus]=useState('');const sequence=useActionSequence(),revision=useRef(0),url=useRef('');useEffect(()=>()=>{if(url.current)URL.revokeObjectURL(url.current)},[]);
 function clear(){if(url.current)URL.revokeObjectURL(url.current);url.current='';setResult(null);setError('');setStatus('')}
 function reset(){sequence.cancel();revision.current++;clear();setValues(['1','100','1']);setUnique(false);setBusy(false)}
 async function run(){if(busy)return;clear();const id=++revision.current,clock=sequence.begin();setBusy(true);try{const n=values.map(v=>v.trim()===''?NaN:Number(v)),text=randomNumbers(n[0],n[1],n[2],unique).join('\n');await clock.finish();if(id!==revision.current)return;url.current=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));setResult({text,url:url.current})}catch(e){if(id===revision.current)setError((e as Error).message)}finally{if(id===revision.current)setBusy(false)}}
 return <><div className="input-grid">{['Minimum (included)','Maximum (included)','How many numbers?'].map((label,index)=><div key={label}><label htmlFor={`random-${index}`} className="field-label">{label}</label><input className="field-input" id={`random-${index}`} type="number" step="1" value={values[index]} disabled={busy} onChange={e=>{clear();setValues(previous=>previous.map((value,i)=>i===index?e.target.value:value))}}/></div>)}</div><label className="aspect-control" htmlFor="random-unique"><span>Unique numbers<small>Prevent repeats within this batch</small></span><Switch id="random-unique" checked={unique} disabled={busy} onCheckedChange={value=>{clear();setUnique(value)}}/></label><div className="button-row"><ActionButton motion="generate" busy={busy} busyLabel="Generating…" completed={!!result} onClick={()=>void run()}>Generate numbers</ActionButton><ResetButton onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div>{error&&<p className="error-message" role="alert">{error}</p>}{result&&<><SuccessNote>Random numbers generated.</SuccessNote><label className="field-label" htmlFor="random-output">Your numbers</label><textarea id="random-output" className="tool-textarea code-textarea" rows={Math.min(8,Number(values[2])+1)} readOnly value={result.text}/><div className="button-row"><CopyButton text={result.text} onStatus={setStatus}/><AnimatedDownloadButton href={result.url} download="toolfera-random-numbers.txt">Download numbers</AnimatedDownloadButton></div></>}<p className="small-note" role="status">{status||'Uses browser cryptographic randomness with unbiased integer selection. Bounds are inclusive. Up to 1,000 numbers, between −1 billion and 1 billion.'}</p></>;
}
