'use client';
import {useState,useId,useEffect,useRef,useMemo} from 'react';
import {useActionSequence} from './use-action-sequence';
import {ActionButton,SuccessNote,ResetButton,CopyButton} from './action-button';
import {Slider} from '@/components/ui/slider';
import {textStats} from '@/tools/math';
export default function TextTools({kind}:{kind:string}){return kind==='word'?<Word/>:kind==='json'?<JSONTool/>:<Password/>}
function Word(){
 const[text,T]=useState('');const id=useId();const small=useMemo(()=>text.length<=50000?textStats(text):null,[text]);
 const[large,setLarge]=useState(textStats('')),[counting,setCounting]=useState(false),[countError,setCountError]=useState('');
 const counter=useRef<Worker|null>(null),revision=useRef(0);
 useEffect(()=>{
  const id=++revision.current;if(small){counter.current?.terminate();counter.current=null;return}
  const failed=()=>{if(id!==revision.current)return;counter.current?.terminate();counter.current=null;setCounting(false);setCountError('Background counting is unavailable. Reload in a recent browser, or use fewer than 50,000 characters.')};
  try{counter.current??=new Worker(new URL('../../tools/text.worker.ts',import.meta.url),{type:'module'});counter.current.onmessage=({data})=>{if(data.id!==revision.current)return;if(data.error){failed();return}setLarge(data.result);setCounting(false)};counter.current.onerror=failed;counter.current.postMessage({id,action:'count',text})}catch{failed()}
 },[text,small]);
 useEffect(()=>()=>{revision.current++;counter.current?.terminate()},[]);
 const s=small||large;return <><label className="field-label" htmlFor={id}>Your text</label><textarea id={id} className="tool-textarea" placeholder="Start typing, or paste your text here…" maxLength={2000000} value={text} onChange={e=>{T(e.target.value);setCountError('');setCounting(e.target.value.length>50000)}}/>{countError?<p className="error-message" role="alert">{countError}</p>:<div className="stat-grid" role="status" aria-live="polite" aria-atomic="true">{[[s.words,'Words'],[s.characters,'Characters'],[s.noSpaces,'Without spaces'],[s.minutes,'Reading minutes']].map(([n,label])=><div className="stat-card" key={label}><strong>{n}</strong><span>{label}</span></div>)}</div>}<div className="button-row"><ResetButton onClick={()=>{T('');setCountError('');setCounting(false)}}>Clear text</ResetButton></div><p className="small-note">{counting?'Counting in the background…':'Reading estimate: 200 words per minute. Up to 2 million characters; text is not saved.'}</p></>
}
function JSONTool(){
 const sequence=useActionSequence();
 const[input,I]=useState('{\n  "hello": "Tool Fera",\n  "useful": true\n}');const[output,O]=useState('');const[error,E]=useState('');const[status,S]=useState('');const[busy,B]=useState(false);const id=useId(),worker=useRef<Worker|null>(null),version=useRef(0);
 const stop=()=>{sequence.cancel();version.current++;worker.current?.terminate();worker.current=null;B(false)};
 useEffect(()=>()=>worker.current?.terminate(),[]);
 const format=(minify:boolean)=>{stop();S('');O('');E('');if(input.length>2000000){E('Use JSON smaller than 2 million characters.');return}try{worker.current=new Worker(new URL('../../tools/text.worker.ts',import.meta.url),{type:'module'});const current=version.current,clock=sequence.begin();B(true);worker.current.onmessage=async({data})=>{if(data.id!==current||current!==version.current)return;worker.current?.terminate();worker.current=null;if(data.error){E(data.error);B(false);return}try{await clock.finish();if(current!==version.current)return;O(data.result);B(false)}catch{/* cancelled */}};worker.current.onerror=()=>{stop();E('Unable to start background formatting. Reload the tool in a recent browser.')};worker.current.postMessage({id:current,action:'json',text:input,minify})}catch{E('This browser does not support background formatting. Use a recent browser.')}};
 return <><label className="field-label" htmlFor={id}>JSON input</label><textarea spellCheck={false} id={id} maxLength={2000001} className="tool-textarea code-textarea" value={input} onChange={e=>{stop();I(e.target.value);O('');E('');S('')}}/><div className="button-row"><ActionButton busy={busy} busyLabel="Processing JSON…" completed={!!output} onClick={()=>format(false)}>Format JSON</ActionButton><ActionButton className="outline-button" busy={busy} busyLabel="Minifying…" onClick={()=>format(true)}>Minify</ActionButton><ResetButton onClick={()=>{stop();I('');O('');E('');S('')}}>{busy?'Cancel & clear':'Clear'}</ResetButton></div>{busy&&<p className="small-note" role="status">Formatting in a background worker…</p>}{error&&<p className="error-message" role="alert">Invalid JSON: {error}</p>}{output&&<><SuccessNote>JSON ready.</SuccessNote><label className="field-label" htmlFor={id+'-out'} style={{marginTop:25}}>Formatted result</label><textarea id={id+'-out'} readOnly className="tool-textarea code-textarea" value={output}/><div className="button-row"><CopyButton text={output} onStatus={S}/></div></>}<p className="small-note" role="status">{status||'Uses JavaScript JSON parsing. Large integers and duplicate keys may change; see the guide below.'}</p></>
}

function securePassword(length:number){const sets=['ABCDEFGHJKLMNPQRSTUVWXYZ','abcdefghijkmnopqrstuvwxyz','23456789','!@#$%&*+-=?'];const alphabet=sets.join('');const pick=(chars:string)=>{const b=new Uint32Array(1);const limit=Math.floor(4294967296/chars.length)*chars.length;do{crypto.getRandomValues(b)}while(b[0]>=limit);return chars[b[0]%chars.length]};const values=sets.map(pick);while(values.length<length)values.push(pick(alphabet));for(let i=values.length-1;i>0;i--){const b=new Uint32Array(1);const limit=Math.floor(4294967296/(i+1))*(i+1);do{crypto.getRandomValues(b)}while(b[0]>=limit);const j=b[0]%(i+1);[values[i],values[j]]=[values[j],values[i]]}return values.join('')}
function Password(){const sequence=useActionSequence(),revision=useRef(0);const[busy,B]=useState(false);const[length,L]=useState(20);const[password,P]=useState('');const[status,S]=useState('');return <><div className="slider-field"><div className="slider-label"><label id="password-length">Password length</label><strong>{length} characters</strong></div><Slider min={12} max={64} step={1} value={[length]} onValueChange={v=>{revision.current++;sequence.cancel();B(false);L(v[0]);P('');S('')}} aria-labelledby="password-length"/></div><p className="small-note">Includes uppercase, lowercase, numbers and symbols.</p><div className="button-row"><ActionButton motion="generate" busy={busy} busyLabel="Generating…" completed={!!password} onClick={async()=>{const id=++revision.current,clock=sequence.begin();B(true);P('');try{const value=securePassword(length);await clock.finish();if(id!==revision.current)return;P(value);S('')}catch{if(id===revision.current)S('Secure random generation is unavailable in this browser.')}finally{if(id===revision.current)B(false)}}}>Generate password</ActionButton></div>{password&&<div className="result-panel"><span className="result-label">Your generated password</span><output className="password-value" aria-live="polite">{password}</output><div className="button-row"><CopyButton text={password} onStatus={S}>Copy password</CopyButton></div></div>}<p className="small-note" role="status">{status||'Generated on your device. Use a unique password for every account and save it in your password manager.'}</p></>}
