'use client';
import {useState,useRef,useEffect} from 'react';
import {Switch} from '@/components/ui/switch';
import {cleanupText,type CleanupOptions} from '@/tools/text-cleanup';
import {useActionSequence} from './use-action-sequence';
import {ActionButton,CopyButton,ResetButton,SuccessNote} from './action-button';
import {AnimatedDownloadButton} from './animated-download-button';
export default function TextCleanupTool({kind}:{kind:'duplicates'|'clean'}){
 const defaults:CleanupOptions={trim:true,collapse:true,empty:false,ignoreCase:false};
 const[text,setText]=useState(''),[options,setOptions]=useState(defaults),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<(ReturnType<typeof cleanupText>&{url:string})|null>(null),[status,setStatus]=useState('');
 const sequence=useActionSequence(),revision=useRef(0),url=useRef('');useEffect(()=>()=>{if(url.current)URL.revokeObjectURL(url.current)},[]);
 function clear(){if(url.current)URL.revokeObjectURL(url.current);url.current='';setResult(null);setError('');setStatus('')}
 function reset(){revision.current++;sequence.cancel();clear();setBusy(false);setText('');setOptions(defaults)}
 async function run(){if(busy)return;clear();const id=++revision.current,clock=sequence.begin();setBusy(true);try{const output=cleanupText(text,kind,options);await clock.finish();if(id!==revision.current)return;url.current=URL.createObjectURL(new Blob([output.text],{type:'text/plain;charset=utf-8'}));setResult({...output,url:url.current})}catch(e){if(id===revision.current)setError((e as Error).message)}finally{if(id===revision.current)setBusy(false)}}
 const switches:[keyof CleanupOptions,string][]=[['trim','Trim spaces at line edges'],...(kind==='duplicates'?[['ignoreCase','Ignore uppercase / lowercase'] as [keyof CleanupOptions,string]]:[['collapse','Collapse repeated spaces and tabs'] as [keyof CleanupOptions,string]]),['empty','Remove empty lines']];
 return <><label className="field-label" htmlFor="cleanup-text">Your text</label><textarea id="cleanup-text" className="tool-textarea" rows={8} value={text} maxLength={200000} disabled={busy} placeholder={kind==='duplicates'?'Paste a list, with one entry per line…':'Paste the text you want to tidy…'} onChange={e=>{clear();setText(e.target.value)}}/><div className="cleanup-options">{switches.map(([key,label])=><label className="aspect-control" key={key} htmlFor={`cleanup-${key}`}><span>{label}</span><Switch id={`cleanup-${key}`} checked={options[key]} disabled={busy} onCheckedChange={value=>{clear();setOptions(previous=>({...previous,[key]:value}))}}/></label>)}</div><div className="button-row"><ActionButton busy={busy} busyLabel="Cleaning…" completed={!!result} onClick={()=>void run()}>{kind==='duplicates'?'Remove duplicates':'Clean text'}</ActionButton><ResetButton onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div>{error&&<p className="error-message" role="alert">{error}</p>}{result&&<><SuccessNote>{kind==='duplicates'?`${result.removed} lines removed. Order preserved.`:'Text cleaned. Review the result.'}</SuccessNote><label className="field-label" htmlFor="cleanup-result">Result · {result.resultLines} lines</label><textarea id="cleanup-result" className="tool-textarea" rows={8} readOnly value={result.text}/><div className="button-row"><CopyButton text={result.text} onStatus={setStatus}/><AnimatedDownloadButton href={result.url} download="toolfera-cleaned-text.txt">Download text</AnimatedDownloadButton></div></>}<p className="small-note" role="status">{status||'Up to 200,000 characters. Line endings normalize to newlines. Text stays in this page; nothing is uploaded or saved.'}</p></>;
}
