'use client';
import {useState,useRef,useEffect} from 'react';
import {useActionSequence} from './use-action-sequence';
import {ActionButton,SuccessNote,ResetButton,CopyButton} from './action-button';
export default function TransformTool({kind}:{kind:'case'|'base64'|'url'}){
 const[text,setText]=useState(''),[output,setOutput]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('upper'),[copy,setCopy]=useState('');
 const sequence=useActionSequence();const worker=useRef<Worker|null>(null),version=useRef(0);useEffect(()=>()=>worker.current?.terminate(),[]);
 const cancel=()=>{sequence.cancel();version.current++;worker.current?.terminate();worker.current=null;setBusy(false)};
 const run=(action:string)=>{cancel();setOutput('');setError('');setCopy('');if(!text){setError('Enter some text first.');return}try{const id=version.current,clock=sequence.begin();worker.current=new Worker(new URL('../../tools/text.worker.ts',import.meta.url),{type:'module'});setBusy(true);worker.current.onmessage=async({data})=>{if(data.id!==id||id!==version.current)return;worker.current?.terminate();worker.current=null;if(data.error){setError(data.error);setBusy(false);return}try{await clock.finish();if(id!==version.current)return;setOutput(data.result);setBusy(false)}catch{/* cancellation releases the sequence */}};worker.current.onerror=()=>{cancel();setError('Unable to start background processing. Reload in a recent browser.')};worker.current.postMessage({id,action:'transform',operation:action,text})}catch{setError('Background processing is unavailable in this browser.')}};
 return <><label className="field-label" htmlFor="transform-input">{kind==='case'?'Your text':kind==='base64'?'Text or Base64':'Text or encoded URL component'}</label><textarea id="transform-input" className="tool-textarea code-textarea" maxLength={2000000} value={text} placeholder={kind==='case'?'Paste the text you want to change…':kind==='base64'?'UTF-8 text, or a standard Base64 value…':'Text, or a percent-encoded component…'} onChange={e=>{cancel();setText(e.target.value);setOutput('');setError('');setCopy('')}}/>{kind==='case'&&<><label className="field-label" htmlFor="text-case">Text case</label><select id="text-case" className="field-input" value={mode} onChange={e=>{cancel();setMode(e.target.value);setOutput('');setError('');setCopy('')}}><option value="upper">UPPERCASE</option><option value="lower">lowercase</option><option value="title">Title Case</option><option value="sentence">Sentence case</option></select></>}
 <div className="button-row">{kind==='case'?<ActionButton busy={busy} busyLabel="Converting…" onClick={()=>run(mode)}>Convert case</ActionButton>:<><ActionButton busy={busy} busyLabel="Processing…" onClick={()=>run(kind+'-encode')}>Encode</ActionButton><ActionButton className="outline-button" busy={busy} busyLabel="Decoding…" onClick={()=>run(kind+'-decode')}>Decode</ActionButton></>}<ResetButton onClick={()=>{cancel();setText('');setOutput('');setError('');setCopy('')}}>{busy?'Cancel & clear':'Clear'}</ResetButton></div>
 {error&&<p className="error-message" role="alert">{error}</p>}{output&&<><SuccessNote>Conversion complete.</SuccessNote><label className="field-label" htmlFor="transform-output">Result</label><textarea id="transform-output" readOnly className="tool-textarea code-textarea" value={output}/><div className="button-row"><CopyButton text={output} onStatus={setCopy}/></div></>}
 <p className="small-note" role="status">{copy||(kind==='base64'?'Base64 is encoding, not encryption. This tool handles UTF-8 text.':kind==='url'?'Encodes one URL component. A plus sign stays a plus sign when decoding.':'Title and sentence case can change acronyms and names. Check the result.')} Text is not saved.</p></>
}
