'use client';
import {useEffect,useRef,useState} from 'react';
import {FileDropZone} from './file-dropzone';
import {useFileFeedback} from './use-file-feedback';
import {friendlyFileError,validatePDF,type ReadReporter} from '@/tools/file-input';
import {ActionButton,ResetButton,SuccessNote} from './action-button';
import {AnimatedDownloadButton} from './animated-download-button';
import {useActionSequence} from './use-action-sequence';
import {fileSize} from '@/tools/image-processing';
import {readDOCX,convertWordPDF} from '@/tools/word-pdf-client';
import type {WordPDFModel,WordPDFBlock} from '@/tools/word-pdf-model';
function documentCounts(blocks:WordPDFBlock[]){const totals={paragraphs:0,tables:0,images:0};for(const block of blocks){if(block.type==='paragraph'&&block.runs.some(run=>run.text.trim()))totals.paragraphs++;else if(block.type==='table')totals.tables++;else if(block.type==='image')totals.images++;else if(block.type==='frame'){const nested=documentCounts(block.blocks);totals.paragraphs+=nested.paragraphs;totals.tables+=nested.tables;totals.images+=nested.images}}return totals}
export default function WordPDFTool(){
 const sequence=useActionSequence(),intake=useFileFeedback();
 const[file,setFile]=useState<File|null>(null),[model,setModel]=useState<WordPDFModel|null>(null),[phase,setPhase]=useState<'empty'|'reading'|'ready'|'building'|'done'>('empty'),[status,setStatus]=useState(''),[error,setError]=useState(''),[result,setResult]=useState<{url:string;bytes:number;pages:number;warnings:string[]}|null>(null);const job=useRef<AbortController|null>(null),revision=useRef(0),url=useRef('');const busy=phase==='reading'||phase==='building';const counts=documentCounts(model?.blocks||[]);
 function clear(){if(url.current)URL.revokeObjectURL(url.current);url.current='';setResult(null)}
 function reset(){intake.reset();sequence.cancel();revision.current++;job.current?.abort();clear();intake.clear();setFile(null);setModel(null);setPhase('empty');setStatus('');setError('')}
 useEffect(()=>()=>{revision.current++;job.current?.abort();if(url.current)URL.revokeObjectURL(url.current)},[]);
 async function choose(files:File[],read?:ReadReporter){if(busy||!files[0])return;reset();const f=files[0],id=++revision.current;const controller=new AbortController();job.current=controller;setPhase('reading');setStatus('Reading Word document…');try{if(!/\.docx$/i.test(f.name))throw new Error('Choose a .docx file. Older .doc files are not supported; save them as DOCX first.');if(f.size>20*1048576)throw new Error('Choose a DOCX up to 20 MB.');setFile(f);const entries=await readDOCX(f,controller.signal,setStatus,read);const {parseDOCX}=await import('@/tools/word-docx-parser');if(controller.signal.aborted)return;const doc=await parseDOCX(entries,controller.signal,setStatus);if(id!==revision.current)return;setModel(doc);setPhase('ready');setStatus('Document ready to convert.')}catch(e){if(id===revision.current){intake.fail(e);setFile(null);setPhase('empty');setStatus('')}}}
 async function convert(){if(!model||busy)return;const clock=sequence.begin();const id=++revision.current;const controller=new AbortController();job.current=controller;clear();setError('');setPhase('building');setStatus('Preparing PDF fonts…');try{const output=await convertWordPDF(model,controller.signal,setStatus);await clock.finish();if(id!==revision.current)return;url.current=URL.createObjectURL(output.blob);setResult({url:url.current,bytes:output.blob.size,pages:output.pages,warnings:output.warnings});setPhase('done');setStatus('PDF ready.')}catch(e){if(id===revision.current){setError(friendlyFileError(e));setPhase('ready');setStatus('')}}}
 const warnings=result?.warnings||model?.warnings||[];
 return <><FileDropZone label="Choose Word file" title={file?file.name:'Drop a Word document here'} description={file?`DOCX · ${fileSize(file.size)}`:'DOCX only · up to 20 MB · processed on your device'} accept=".docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document" selected={!!file} disabled={busy} busy={phase==='reading'} status={status} error={intake.error} resetKey={intake.resetKey} onFiles={(files,read)=>choose(files,read)}/><p className="word-review-note">Creates a real PDF with selectable text, headings, paragraphs, lists, PNG/JPEG images and basic tables. Explicit and saved page breaks, section margins and intentional blank space are preserved. Simple saved header/footer text and positioned PNG/JPEG images are supported. Complex layouts and font substitutions still need review. No OCR is used.</p>{model&&<div className="word-analysis"><strong>Word document prepared</strong><p>{counts.paragraphs} paragraphs · {counts.tables} tables · {counts.images} images</p><ul>{warnings.map(note=><li key={note}>{note}</li>)}</ul></div>}<div className="button-row"><ActionButton disabled={!model} busy={busy} busyLabel="Converting…" completed={!!result} motion="convert" onClick={()=>void convert()}>Convert to PDF</ActionButton><ResetButton onClick={reset}>{busy?'Cancel & reset':'Reset'}</ResetButton></div><p role="status" className="image-status">{status}</p>{error&&<p role="alert" className="error-message">{error}</p>}{result&&file&&<><SuccessNote>PDF created. Review the pages before sharing.</SuccessNote><div className="result-panel"><span className="result-label">Your PDF document</span><strong className="pdf-result">{result.pages} pages · {fileSize(result.bytes)}</strong><div className="button-row"><AnimatedDownloadButton href={result.url} download={file.name.replace(/\.docx$/i,'')+'.pdf'}>Download PDF</AnimatedDownloadButton></div></div></>}<p className="small-note">No upload or conversion service. Archive contents are capped at 32 MB; text at 200,000 characters and PDF output at 100 pages / 40 MB. Font assets load only for this tool. Review unsupported elements and font substitutions.</p></>;
}
