export function generateUUIDs(count:number){if(!Number.isInteger(count)||count<1||count>100)throw new Error('Choose a whole-number count from 1 to 100.');return Array.from({length:count},()=>{if(typeof crypto.randomUUID==='function')return crypto.randomUUID();const b=crypto.getRandomValues(new Uint8Array(16));b[6]=(b[6]&15)|64;b[8]=(b[8]&63)|128;const h=Array.from(b,n=>n.toString(16).padStart(2,'0')).join('');return `${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`})}
export type ConvertedColor={hex:string;rgb:string;hsl:string;r:number;g:number;b:number;alpha:number};
export function convertColor(input:string):ConvertedColor{
 if(input.length>200)throw new Error('Enter one color, up to 200 characters.');const s=input.trim().toLowerCase();let r=0,g=0,b=0,a=1;const hex=s.match(/^#?([0-9a-f]{3}|[0-9a-f]{4}|[0-9a-f]{6}|[0-9a-f]{8})$/),fn=s.match(/^(rgba?|hsla?)\(([^()]*)\)$/);
 const error=()=>new Error('Use HEX, RGB or HSL, for example #2f5bff, rgb(47, 91, 255), or hsl(227, 100%, 59%).');
 const n=(v:string,max:number,percent=false)=>{if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)%?$/.test(v)||(!percent&&v.endsWith('%')))throw error();const x=Number(v.replace('%',''));if(!Number.isFinite(x)||x<0||x>(v.endsWith('%')?100:max))throw new Error(`Color values must stay within ${v.endsWith('%')?'0–100%':`0–${max}`}.`);return v.endsWith('%')?x/100*max:x};
 if(hex){let h=hex[1];if(h.length<5)h=Array.from(h,c=>c+c).join('');r=parseInt(h.slice(0,2),16);g=parseInt(h.slice(2,4),16);b=parseInt(h.slice(4,6),16);if(h.length===8)a=parseInt(h.slice(6,8),16)/255}
 else if(fn){const raw=fn[2].trim(),comma=raw.includes(','),slash=raw.split('/');let parts:string[];if(comma){if(slash.length!==1)throw error();parts=raw.split(',').map(v=>v.trim());if(parts.some(v=>!v))throw error()}else{if(slash.length>2)throw error();parts=slash[0].trim().split(/\s+/);if(parts.length!==3)throw error();if(slash.length===2){if(!slash[1].trim())throw error();parts.push(slash[1].trim())}}if(parts.length<3||parts.length>4)throw error();if(parts[3])a=n(parts[3],1,true);if(fn[1].startsWith('rgb')){[r,g,b]=parts.slice(0,3).map(v=>n(v,255,true))}else{if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)(?:deg)?$/.test(parts[0])||!parts[1].endsWith('%')||!parts[2].endsWith('%'))throw error();const hue=Number(parts[0].replace('deg',''));if(!Number.isFinite(hue))throw error();const h=((hue%360)+360)%360/360,sat=n(parts[1],1,true),l=n(parts[2],1,true),m=sat*Math.min(l,1-l);const channel=(offset:number)=>{const k=(offset+h*12)%12;return 255*(l-m*Math.max(-1,Math.min(k-3,9-k,1)))};[r,g,b]=[channel(0),channel(8),channel(4)]}}
 else throw error();[r,g,b]=[r,g,b].map(Math.round);const max=Math.max(r,g,b)/255,min=Math.min(r,g,b)/255,delta=max-min,l=(max+min)/2;let h=0,sat=0;if(delta){sat=delta/(1-Math.abs(2*l-1));h=(max===r/255?(g-b)/255/delta+(g<b?6:0):max===g/255?(b-r)/255/delta+2:(r-g)/255/delta+4)*60}const fmt=(x:number)=>String(Math.round(x*10)/10),alpha=String(Math.round(a*1000)/1000),hexOut='#'+[r,g,b,...(a<1?[Math.round(a*255)]:[])].map(x=>x.toString(16).padStart(2,'0')).join('');return{hex:hexOut,rgb:a<1?`rgba(${r}, ${g}, ${b}, ${alpha})`:`rgb(${r}, ${g}, ${b})`,hsl:a<1?`hsla(${fmt(h)}, ${fmt(sat*100)}%, ${fmt(l*100)}%, ${alpha})`:`hsl(${fmt(h)}, ${fmt(sat*100)}%, ${fmt(l*100)}%)`,r,g,b,alpha:a};
}
