import {zipSync,strToU8} from 'fflate';
import type {WordDocument,WordRun,WordParagraph,WordBlock,WordPage} from './pdf-word-layout.ts';
const w='http://schemas.openxmlformats.org/wordprocessingml/2006/main',r='http://schemas.openxmlformats.org/officeDocument/2006/relationships';
const xml=(body:string)=>'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'+body;
const esc=(s:string)=>s.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]!));
const tw=(pt:number)=>Math.round(pt*20);
function runXML(run:WordRun){if(run.break)return'<w:r><w:br/></w:r>';const size=Math.max(12,Math.min(144,Math.round(run.size*2)));return`<w:r><w:rPr><w:rFonts w:ascii="${esc(run.font)}" w:hAnsi="${esc(run.font)}" w:cs="${esc(run.font)}"/><w:sz w:val="${size}"/><w:szCs w:val="${size}"/>${run.bold?'<w:b/><w:bCs/>':''}${run.italic?'<w:i/><w:iCs/>':''}${run.rtl?'<w:rtl/>':''}</w:rPr><w:t xml:space="preserve">${esc(run.text)}</w:t></w:r>`}
function paragraphXML(p:WordParagraph,page:WordPage,before=0){const indent=p.align==='center'?0:Math.max(0,Math.min(tw(page.width-page.left-page.right-36),tw(p.x-page.left)));return`<w:p><w:pPr>${p.heading?`<w:pStyle w:val="Heading${p.heading}"/>`:''}<w:widowControl w:val="0"/><w:keepNext w:val="0"/>${p.list?`<w:numPr><w:ilvl w:val="0"/><w:numId w:val="${p.listGroup}"/></w:numPr>`:''}<w:ind w:left="${indent+(p.list?360:0)}"${p.list?' w:hanging="360"':''}/><w:spacing w:before="${tw(before)}" w:after="${tw(p.after)}" w:line="${tw(p.lineHeight||p.size*1.2)}" w:lineRule="exact"/>${p.rtl?'<w:bidi/>':''}<w:jc w:val="${p.align|| (p.rtl?'right':'left')}"/></w:pPr>${p.runs.map(runXML).join('')}</w:p>`}
function section(page:WordPage,last:boolean){return`<w:sectPr>${!last?'<w:type w:val="nextPage"/>':''}<w:pgSz w:w="${tw(page.width)}" w:h="${tw(page.height)}"${page.width>page.height?' w:orient="landscape"':''}/><w:pgMar w:top="${tw(page.top)}" w:right="${tw(page.right)}" w:bottom="720" w:left="${tw(page.left)}" w:header="0" w:footer="0" w:gutter="0"/></w:sectPr>`}
export function packageDOCX(model:WordDocument){
 const entries:Record<string,Uint8Array>={},relationships:string[]=[],listGroups=new Map<number,{type:string;start:number}>();let imageId=0;
 function flow(blocks:WordBlock[],page:WordPage){let cursor=page.top;return blocks.map(block=>{const before=Math.max(0,block.y-cursor);const prefix=block.type!=='paragraph'&&block.type!=='image'&&before>.5?`<w:p><w:pPr><w:spacing w:before="0" w:after="0" w:line="${tw(before)}" w:lineRule="exact"/></w:pPr></w:p>`:'';if(block.type!=='image')cursor=Math.max(cursor,block.y+(block.height||(block.type==='paragraph'?block.size*1.2:24))+(block.type==='paragraph'?block.after:0));return prefix+blockXML(block,page,before)}).join('')}
 function blockXML(block:WordBlock,page:WordPage,before=0):string{
  if(block.type==='paragraph'){if(block.list)listGroups.set(block.listGroup!,{type:block.list,start:listGroups.get(block.listGroup!)?.start??block.listStart??1});return paragraphXML(block,page,before)}
  if(block.type==='columns'){const widths=block.columns.map(c=>tw(c.width));return`<w:tbl><w:tblPr><w:tblLayout w:type="fixed"/><w:tblInd w:w="${tw(Math.max(0,block.x-page.left))}" w:type="dxa"/><w:tblBorders>${['top','left','bottom','right','insideH','insideV'].map(edge=>`<w:${edge} w:val="nil"/>`).join('')}</w:tblBorders><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:left w:w="0" w:type="dxa"/><w:right w:w="0" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>${widths.map(v=>`<w:gridCol w:w="${v}"/>`).join('')}</w:tblGrid><w:tr><w:trPr><w:cantSplit/></w:trPr>${block.columns.map((column,i)=>`<w:tc><w:tcPr><w:tcW w:w="${widths[i]}" w:type="dxa"/><w:vAlign w:val="top"/></w:tcPr>${flow(column.blocks,{...page,left:column.x,right:page.width-column.x-column.width,top:block.y})}<w:p><w:pPr><w:spacing w:line="20" w:lineRule="exact" w:after="0"/></w:pPr></w:p></w:tc>`).join('')}</w:tr></w:tbl>`}
  if(block.type==='table'){const available=page.width-page.left-page.right-Math.max(0,block.x-page.left),scale=Math.min(1,available/block.widths.reduce((a,b)=>a+b,0));const widths=block.widths.map(v=>tw(v*scale));return`<w:tbl><w:tblPr><w:tblInd w:w="${tw(Math.max(0,block.x-page.left))}" w:type="dxa"/><w:tblW w:w="${widths.reduce((a,b)=>a+b,0)}" w:type="dxa"/><w:tblLayout w:type="fixed"/><w:tblBorders>${['top','left','bottom','right','insideH','insideV'].map(edge=>`<w:${edge} w:val="single" w:sz="4" w:color="D9D9D9"/>`).join('')}</w:tblBorders><w:tblCellMar><w:top w:w="0" w:type="dxa"/><w:left w:w="60" w:type="dxa"/><w:bottom w:w="0" w:type="dxa"/><w:right w:w="60" w:type="dxa"/></w:tblCellMar></w:tblPr><w:tblGrid>${widths.map(v=>`<w:gridCol w:w="${v}"/>`).join('')}</w:tblGrid>${block.rows.map((row,index)=>`<w:tr><w:trPr><w:cantSplit/>${index===0&&block.header?'<w:tblHeader/>':''}${block.rowHeights?.[index]?`<w:trHeight w:val="${tw(block.rowHeights[index])}" w:hRule="atLeast"/>`:''}</w:trPr>${row.map((rs,col)=>`<w:tc><w:tcPr><w:tcW w:w="${widths[col]}" w:type="dxa"/><w:vAlign w:val="center"/></w:tcPr><w:p><w:pPr><w:spacing w:after="0" w:line="${tw(Math.max(...rs.map(r=>r.size),10)*1.2)}" w:lineRule="exact"/></w:pPr>${rs.map(runXML).join('')}</w:p></w:tc>`).join('')}</w:tr>`).join('')}</w:tbl>`}
  const image=block.image,id=++imageId,name=`image${id}.png`,rid=`rIdImage${id}`;entries[`word/media/${name}`]=image.bytes;relationships.push(`<Relationship Id="${rid}" Type="${r}/image" Target="media/${name}"/>`);
  const available=page.width-page.left-page.right,indent=Math.max(0,Math.min(available-36,block.x-page.left));
  const scale=Math.min(1,(available-indent)/image.width,(page.height-page.top-36)*.85/image.height),cx=Math.round(image.width*scale*12700),cy=Math.round(image.height*scale*12700);
  return`<w:p><w:pPr><w:spacing w:before="0" w:after="0" w:line="20" w:lineRule="exact"/></w:pPr><w:r><w:drawing><wp:anchor distT="0" distB="0" distL="0" distR="0" simplePos="0" relativeHeight="${id}" behindDoc="0" locked="0" layoutInCell="1" allowOverlap="1"><wp:simplePos x="0" y="0"/><wp:positionH relativeFrom="page"><wp:posOffset>${Math.round((page.left+indent)*12700)}</wp:posOffset></wp:positionH><wp:positionV relativeFrom="page"><wp:posOffset>${Math.round(image.y*12700)}</wp:posOffset></wp:positionV><wp:extent cx="${cx}" cy="${cy}"/><wp:wrapNone/><wp:docPr id="${id}" name="Image ${id}" descr="Image from source PDF"/><wp:cNvGraphicFramePr><a:graphicFrameLocks noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic><pic:nvPicPr><pic:cNvPr id="${id}" name="${name}"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip r:embed="${rid}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${cx}" cy="${cy}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:anchor></w:drawing></w:r></w:p>`;
 }
 const body=model.pages.map((page,i)=>flow(page.blocks,page)+(i<model.pages.length-1?`<w:p><w:pPr><w:spacing w:line="20" w:lineRule="exact" w:after="0"/>${section(page,false)}</w:pPr></w:p>`:section(page,true))).join('');
 const parts:Record<string,string>={
 '[Content_Types].xml':xml(`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Default Extension="png" ContentType="image/png"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/word/numbering.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.numbering+xml"/></Types>`),
 '_rels/.rels':xml(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdDocument" Type="${r}/officeDocument" Target="word/document.xml"/></Relationships>`),
 'word/document.xml':xml(`<w:document xmlns:w="${w}" xmlns:r="${r}" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing" xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><w:body>${body}</w:body></w:document>`),
 'word/_rels/document.xml.rels':xml(`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rIdStyles" Type="${r}/styles" Target="styles.xml"/><Relationship Id="rIdNumbering" Type="${r}/numbering" Target="numbering.xml"/>${relationships.join('')}</Relationships>`),
 'word/styles.xml':xml(`<w:styles xmlns:w="${w}"><w:docDefaults><w:rPrDefault><w:rPr><w:rFonts w:ascii="Calibri" w:hAnsi="Calibri"/><w:sz w:val="22"/></w:rPr></w:rPrDefault></w:docDefaults><w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>${[1,2,3].map(n=>`<w:style w:type="paragraph" w:styleId="Heading${n}"><w:name w:val="heading ${n}"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:qFormat/><w:pPr><w:keepNext/><w:outlineLvl w:val="${n-1}"/></w:pPr><w:rPr><w:b/></w:rPr></w:style>`).join('')}</w:styles>`),
 'word/numbering.xml':xml(`<w:numbering xmlns:w="${w}">${['bullet','decimal'].map((type,i)=>`<w:abstractNum w:abstractNumId="${i}"><w:multiLevelType w:val="singleLevel"/><w:lvl w:ilvl="0"><w:start w:val="1"/><w:numFmt w:val="${type}"/><w:lvlText w:val="${type==='bullet'?'•':'%1.'}"/><w:lvlJc w:val="left"/></w:lvl></w:abstractNum>`).join('')}${[...listGroups].map(([id,{type,start}])=>`<w:num w:numId="${id}"><w:abstractNumId w:val="${type==='bullet'?0:1}"/><w:lvlOverride w:ilvl="0"><w:startOverride w:val="${start}"/></w:lvlOverride></w:num>`).join('')}</w:numbering>`)
 };
 for(const[name,content]of Object.entries(parts))entries[name]=strToU8(content);
 const bytes=zipSync(entries,{level:6});if(bytes.length>40*1048576)throw new Error('The Word document exceeds 40 MB. Convert fewer pages.');
 return new Blob([bytes as Uint8Array<ArrayBuffer>],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'});
}
