import {readFileBytes} from './file-input';
import {inspectImageHeader} from './image-input';
import {dimensions,validateCrop,encodeBMP,type ImageSettings,type ProcessedImage} from './image-processing';
import type {ImageProcessor} from './image-client';
export async function createCompatibilityProcessor():Promise<ImageProcessor>{
 let source:HTMLImageElement|undefined,url:string|undefined,disposed=false;
 const toBlob=(canvas:HTMLCanvasElement,mime:string,quality:number)=>new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Unable to export this image.')),mime,quality));
 const test=document.createElement('canvas');test.width=test.height=1;const formats=['image/bmp'];for(const mime of ['image/jpeg','image/png','image/webp','image/avif']){try{if((await toBlob(test,mime,.8)).type===mime)formats.push(mime)}catch{}}
 return {formats,compatibility:true,inspect:async(file,read)=>{const bytes=new Uint8Array(await readFileBytes(file,undefined,read)),header=inspectImageHeader(bytes,4_000_000);if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(new Blob([bytes],{type:header.mime}));const image=new Image();image.src=url;await image.decode();if(disposed)throw new Error('Processing cancelled.');if(image.naturalWidth*image.naturalHeight>4000000)throw new Error('This browser uses the compatibility processor, limited to 4 million pixels. Use a recent browser for larger images.');source=image;return {width:image.naturalWidth,height:image.naturalHeight,bytes:file.size,mime:file.type}},process:async(settings:ImageSettings):Promise<ProcessedImage>=>{if(!source)throw new Error('Choose an image first.');const d=dimensions(source.naturalWidth,source.naturalHeight,settings.width,settings.height,settings.mode);if(d.width*d.height>4000000)throw new Error('The compatibility processor is limited to 4 million output pixels.');await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));const canvas=document.createElement('canvas');canvas.width=d.width;canvas.height=d.height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas processing is unavailable.');if(['image/jpeg','image/bmp'].includes(settings.mime)){ctx.fillStyle='#fff';ctx.fillRect(0,0,d.width,d.height)}ctx.imageSmoothingQuality='high';if(settings.crop){const c=validateCrop(source.naturalWidth,source.naturalHeight,settings.crop);ctx.drawImage(source,c.x,c.y,c.width,c.height,0,0,d.width,d.height)}else {ctx.drawImage(source,(d.width-d.drawWidth)/2,(d.height-d.drawHeight)/2,d.drawWidth,d.drawHeight);}const blob=settings.mime==='image/bmp'?encodeBMP(ctx.getImageData(0,0,d.width,d.height).data,d.width,d.height):await toBlob(canvas,settings.mime,settings.quality/100);if(blob.type!==settings.mime)throw new Error('This browser cannot export the selected format.');return {blob,width:d.width,height:d.height,bytes:blob.size,mime:blob.type}},dispose:()=>{disposed=true;source=undefined;if(url)URL.revokeObjectURL(url)}};
}
