import {readFileBytes,type ReadReporter} from './file-input.ts';
import * as pdfjs from 'pdfjs-dist';
import type {PDFWordPage} from './pdf-word-layout';
const assets='/_pdfjs/v5.4.624/';
pdfjs.GlobalWorkerOptions.workerSrc=assets+'pdf.worker.min.mjs';
import {createOCRWorker,ocrLanguages} from './ocr-worker-client.ts';
import {prepareOCRImage,turnOCRImage} from './ocr-preprocess.ts';
import {ocrPageLayout} from './ocr-layout.ts';
export {createOCRWorker} from './ocr-worker-client.ts';
export async function ocrPDF(file:File,raw:{pages:PDFWordPage[];warnings:string[];scans:number[]}|null,signal:AbortSignal,progress:(message:string)=>void,language:keyof typeof ocrLanguages='eng'){
 const mobile=window.matchMedia('(max-width: 767px)').matches;const pageLimit=mobile?5:10,byteLimit=(mobile?5:10)*1048576;
 if(file.size>byteLimit||(raw?.scans.length||0)>pageLimit)throw new Error(`OCR on ${mobile?'mobile':'this device'} supports up to ${pageLimit} scanned pages and ${mobile?5:10} MB. Split the PDF into smaller parts first.`);
 const loading=pdfjs.getDocument({data:new Uint8Array(await readFileBytes(file,signal)),isEvalSupported:false,canvasMaxAreaInBytes:8*1048576,maxImageSize:40000000,cMapUrl:assets+'cmaps/',cMapPacked:true,standardFontDataUrl:assets+'standard_fonts/',wasmUrl:assets+'wasm/'});
 let render:ReturnType<pdfjs.PDFPageProxy['render']>|undefined,currentPage=0,totalPages=raw?.scans.length||0;const worker=createOCRWorker(signal,(status,fraction)=>{if(status==='recognizing text')progress(`OCR page ${currentPage} of ${totalPages}${typeof fraction==='number'?` · ${Math.round(Math.max(0,Math.min(1,fraction))*100)}%`:''}`);else progress(status==='loading language traineddata'?'Loading English OCR language…':status==='loading tesseract core'?'Loading OCR engine…':'Preparing OCR…')});
 const abort=()=>{render?.cancel();void loading.destroy()};signal.addEventListener('abort',abort,{once:true});
 try{if(signal.aborted)throw new DOMException('Cancelled','AbortError');const doc=await loading.promise;if(!raw&&doc.numPages>pageLimit)throw new Error(`OCR on ${mobile?'mobile':'this device'} supports up to ${pageLimit} scanned pages and ${mobile?5:10} MB. Split the PDF into smaller parts first.`);const scans=raw?.scans||Array.from({length:doc.numPages},(_,i)=>i+1);totalPages=scans.length;progress('Loading OCR engine…');await worker.initialize(language);const pages:PDFWordPage[]=raw?[...raw.pages]:Array.from({length:doc.numPages},()=>({width:595.28,height:841.89,text:[],images:[]})),warnings=[...(raw?.warnings||[]),'OCR text can contain recognition errors. Review names, numbers and formatting before sharing.'];
  for(const number of scans){if(signal.aborted)throw new DOMException('Cancelled','AbortError');currentPage++;progress(`Rendering OCR page ${currentPage} of ${totalPages}…`);const page=await doc.getPage(number),points=page.getViewport({scale:1});const scale=Math.min(150/72,Math.sqrt((mobile?1800000:3000000)/(points.width*points.height)));const viewport=page.getViewport({scale}),canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);const ctx=canvas.getContext('2d');if(!ctx)throw new Error('OCR rendering is unavailable in this browser.');
   try{render=page.render({canvas,canvasContext:ctx,viewport,background:'rgb(255,255,255)'});await render.promise;render=undefined;const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Unable to prepare a scanned page.')),'image/png'));canvas.width=canvas.height=0;const prepared=await prepareOCRImage(new Uint8Array(await blob.arrayBuffer()),signal,progress);let result=await worker.recognize(prepared.bytes.slice());if(prepared.sideways&&result.confidence<65){progress('Checking text orientation…');const alternate=await worker.recognize(await turnOCRImage(prepared.bytes,signal));if(alternate.confidence>result.confidence)result=alternate}if(signal.aborted)throw new DOMException('Cancelled','AbortError');if(result.text.replace(/\s/g,'').length<20)throw new Error(`Page ${number} has too little readable text for a useful Word document. Try a clearer, upright English scan.`);
    const width=prepared.sideways?points.height:points.width,height=prepared.sideways?points.width:points.height;
    const reconstructed=ocrPageLayout(result,width,height,prepared.width/width);if(!reconstructed.text.length)throw new Error('OCR could not reconstruct editable text. Try a clearer scan.');if(result.confidence<70)warnings.push(`Page ${number} has low OCR confidence; check its text carefully.`);pages[number-1]=reconstructed;if(pages.reduce((sum,p)=>sum+p.text.reduce((n,item)=>n+item.text.length,0),0)>200000)throw new Error('The recognized text exceeds 200,000 characters. Split a smaller selection.');progress(`OCR page ${currentPage} of ${totalPages} complete.`);
   }finally{canvas.width=canvas.height=0;page.cleanup()}
  }return{pages,warnings};
 }catch(e){if(signal.aborted)throw new DOMException('Cancelled','AbortError');throw e}finally{worker.dispose();signal.removeEventListener('abort',abort);await loading.destroy()}
}

export async function inspectOCRPDF(file:File,signal:AbortSignal,progress:(message:string)=>void,read?:ReadReporter){const mobile=window.matchMedia('(max-width:767px)').matches,limit=mobile?5:10;if(file.size>limit*1048576)throw new Error(`Choose a PDF up to ${limit} MB for OCR.`);progress('Reading PDF…');const loading=pdfjs.getDocument({data:new Uint8Array(await readFileBytes(file,signal,read)),isEvalSupported:false});const abort=()=>{void loading.destroy()};signal.addEventListener('abort',abort,{once:true});try{if(signal.aborted)throw new DOMException('Cancelled','AbortError');const doc=await loading.promise;if(await doc.getPermissions())throw new Error('Encrypted/password-protected PDFs are unsupported. Use an unencrypted copy.');if(doc.numPages>limit)throw new Error(`Choose a PDF with at most ${limit} pages for OCR. Split larger documents first.`);return{pages:doc.numPages}}catch(e){if(signal.aborted)throw new DOMException('Cancelled','AbortError');if((e as Error).name==='PasswordException')throw new Error('Encrypted/password-protected PDFs are unsupported. Use an unencrypted copy.');throw e}finally{signal.removeEventListener('abort',abort);await loading.destroy()}}
